var namespaces =
[
    [ "alerts", "d2/de9/namespacealerts.html", "d2/de9/namespacealerts" ],
    [ "cache", "db/d8d/namespacecache.html", "db/d8d/namespacecache" ],
    [ "compiler", "da/d79/namespacecompiler.html", "da/d79/namespacecompiler" ],
    [ "components", "d0/d1f/namespacecomponents.html", "d0/d1f/namespacecomponents" ],
    [ "concurrent", "df/d2b/namespaceconcurrent.html", "df/d2b/namespaceconcurrent" ],
    [ "congestion_control", "d7/d22/namespacecongestion__control.html", "d7/d22/namespacecongestion__control" ],
    [ "crypto", "de/d36/namespacecrypto.html", "de/d36/namespacecrypto" ],
    [ "decimal64", "da/d81/namespacedecimal64.html", "da/d81/namespacedecimal64" ],
    [ "dist_lock", "da/d4a/namespacedist__lock.html", "da/d4a/namespacedist__lock" ],
    [ "drivers", "d3/de1/namespacedrivers.html", "d3/de1/namespacedrivers" ],
    [ "dump", "d8/d72/namespacedump.html", "d8/d72/namespacedump" ],
    [ "engine", "dc/d3f/namespaceengine.html", "dc/d3f/namespaceengine" ],
    [ "error_injection", "d6/dca/namespaceerror__injection.html", "d6/dca/namespaceerror__injection" ],
    [ "formats", "d8/d5b/namespaceformats.html", "d8/d5b/namespaceformats" ],
    [ "fs", "d5/d8f/namespacefs.html", "d5/d8f/namespacefs" ],
    [ "hostinfo", "d7/d9e/namespacehostinfo.html", "d7/d9e/namespacehostinfo" ],
    [ "http", "d3/d69/namespacehttp.html", "d3/d69/namespacehttp" ],
    [ "logging", "dd/d46/namespacelogging.html", "dd/d46/namespacelogging" ],
    [ "os_signals", "d5/d79/namespaceos__signals.html", "d5/d79/namespaceos__signals" ],
    [ "pytest_userver", "d3/d88/namespacepytest__userver.html", "d3/d88/namespacepytest__userver" ],
    [ "rcu", "dd/dde/namespacercu.html", "dd/dde/namespacercu" ],
    [ "std", "d8/dcc/namespacestd.html", "d8/dcc/namespacestd" ],
    [ "storages", "d0/d91/namespacestorages.html", "d0/d91/namespacestorages" ],
    [ "testsuite", "d3/d56/namespacetestsuite.html", "d3/d56/namespacetestsuite" ],
    [ "tracing", "d2/de2/namespacetracing.html", "d2/de2/namespacetracing" ],
    [ "ugrpc", "d0/d87/namespaceugrpc.html", "d0/d87/namespaceugrpc" ],
    [ "utest", "de/d3a/namespaceutest.html", "de/d3a/namespaceutest" ],
    [ "utils", "d6/d84/namespaceutils.html", "d6/d84/namespaceutils" ],
    [ "yaml_config", "dd/d20/namespaceyaml__config.html", "dd/d20/namespaceyaml__config" ]
];