var searchData=
[
  ['randombase_0',['RandomBase',['../d1/d26/classutils_1_1RandomBase.html',1,'utils']]],
  ['range_1',['Range',['../d1/df6/classstorages_1_1postgres_1_1Range.html',1,'storages::postgres']]],
  ['rangeoptions_2',['RangeOptions',['../d2/df8/structredis_1_1RangeOptions.html',1,'redis']]],
  ['rangescoreoptions_3',['RangeScoreOptions',['../d0/dca/structredis_1_1RangeScoreOptions.html',1,'redis']]],
  ['rcumap_4',['RcuMap',['../d0/d1f/classrcu_1_1RcuMap.html',1,'rcu']]],
  ['rcumap_3c_20std_3a_3astring_2c_20clients_3a_3ahttp_3a_3astatistics_20_3e_5',['RcuMap&lt; std::string, clients::http::Statistics &gt;',['../d0/d1f/classrcu_1_1RcuMap.html',1,'rcu']]],
  ['rcumapiterator_6',['RcuMapIterator',['../d8/de4/classrcu_1_1RcuMapIterator.html',1,'rcu']]],
  ['readablebase_7',['ReadableBase',['../da/d1b/classengine_1_1io_1_1ReadableBase.html',1,'engine::io']]],
  ['readableptr_8',['ReadablePtr',['../dd/df3/classrcu_1_1ReadablePtr.html',1,'rcu']]],
  ['reader_9',['Reader',['../d2/d03/classdump_1_1Reader.html',1,'dump']]],
  ['readpreference_10',['ReadPreference',['../dc/db5/classstorages_1_1mongo_1_1options_1_1ReadPreference.html',1,'storages::mongo::options']]],
  ['recentperiod_11',['RecentPeriod',['../d2/d67/classutils_1_1statistics_1_1RecentPeriod.html',1,'utils::statistics']]],
  ['recentperiod_3c_20percentile_3c_202000_2c_20unsigned_20int_2c_201180_2c_20100_20_3e_2c_20percentile_3c_202000_2c_20unsigned_20int_2c_201180_2c_20100_20_3e_2c_20utils_3a_3adatetime_3a_3asteadyclock_20_3e_12',['RecentPeriod&lt; Percentile&lt; 2000, unsigned int, 1180, 100 &gt;, Percentile&lt; 2000, unsigned int, 1180, 100 &gt;, utils::datetime::SteadyClock &gt;',['../d2/d67/classutils_1_1statistics_1_1RecentPeriod.html',1,'utils::statistics']]],
  ['recentperiod_3c_20percentile_3c_202048_20_3e_2c_20percentile_3c_202048_20_3e_2c_20utils_3a_3adatetime_3a_3asteadyclock_20_3e_13',['RecentPeriod&lt; Percentile&lt; 2048 &gt;, Percentile&lt; 2048 &gt;, utils::datetime::SteadyClock &gt;',['../d2/d67/classutils_1_1statistics_1_1RecentPeriod.html',1,'utils::statistics']]],
  ['recvfromresult_14',['RecvFromResult',['../dc/d72/structengine_1_1io_1_1Socket_1_1RecvFromResult.html',1,'engine::io::Socket']]],
  ['redis_15',['Redis',['../d6/dd0/classcomponents_1_1Redis.html',1,'components']]],
  ['rediscontrol_16',['RedisControl',['../d4/dfe/structtestsuite_1_1RedisControl.html',1,'testsuite']]],
  ['redissettings_17',['RedisSettings',['../d7/d05/structsecdist_1_1RedisSettings.html',1,'secdist']]],
  ['rediswaitconnected_18',['RedisWaitConnected',['../d1/dd5/structredis_1_1RedisWaitConnected.html',1,'redis']]],
  ['refillpolicy_19',['RefillPolicy',['../de/d15/structutils_1_1TokenBucket_1_1RefillPolicy.html',1,'utils::TokenBucket']]],
  ['regex_20',['regex',['../dd/d3e/classutils_1_1regex.html',1,'utils']]],
  ['relaxedcounter_21',['RelaxedCounter',['../d9/d48/classutils_1_1statistics_1_1RelaxedCounter.html',1,'utils::statistics']]],
  ['relaxedcounter_3c_20size_5ft_20_3e_22',['RelaxedCounter&lt; size_t &gt;',['../d9/d48/classutils_1_1statistics_1_1RelaxedCounter.html',1,'utils::statistics']]],
  ['relaxedcounter_3c_20valuetype_20_3e_23',['RelaxedCounter&lt; ValueType &gt;',['../d9/d48/classutils_1_1statistics_1_1RelaxedCounter.html',1,'utils::statistics']]],
  ['removetuplereferences_24',['RemoveTupleReferences',['../d1/d86/structstorages_1_1postgres_1_1io_1_1traits_1_1RemoveTupleReferences.html',1,'storages::postgres::io::traits']]],
  ['removetuplereferences_3c_20std_3a_3atuple_3c_20t_2e_2e_2e_20_3e_20_3e_25',['RemoveTupleReferences&lt; std::tuple&lt; T... &gt; &gt;',['../d7/dd1/structstorages_1_1postgres_1_1io_1_1traits_1_1RemoveTupleReferences_3_01std_1_1tuple_3_01T_8_8_8_01_4_01_4.html',1,'storages::postgres::io::traits']]],
  ['replaceone_26',['ReplaceOne',['../d4/d75/classstorages_1_1mongo_1_1bulk__ops_1_1ReplaceOne.html',1,'storages::mongo::bulk_ops::ReplaceOne'],['../d5/de4/classstorages_1_1mongo_1_1operations_1_1ReplaceOne.html',1,'storages::mongo::operations::ReplaceOne']]],
  ['reply_27',['Reply',['../d7/dc1/structdynamic__config_1_1Client_1_1Reply.html',1,'dynamic_config::Client::Reply'],['../dd/d1a/classredis_1_1Reply.html',1,'redis::Reply']]],
  ['replydata_28',['ReplyData',['../dd/dc7/classredis_1_1ReplyData.html',1,'redis']]],
  ['replyelemholder_29',['ReplyElemHolder',['../dc/da7/classstorages_1_1redis_1_1ScanRequest_1_1Iterator_1_1ReplyElemHolder.html',1,'storages::redis::ScanRequest::Iterator']]],
  ['replyptrfuture_30',['ReplyPtrFuture',['../d0/db4/classredis_1_1ReplyPtrFuture.html',1,'redis']]],
  ['replyptrpromise_31',['ReplyPtrPromise',['../d4/df9/classredis_1_1ReplyPtrPromise.html',1,'redis']]],
  ['request_32',['Request',['../de/df5/classclients_1_1http_1_1Request.html',1,'clients::http::Request'],['../d5/de1/classredis_1_1Request.html',1,'redis::Request'],['../dc/d4a/classstorages_1_1redis_1_1Request.html',1,'storages::redis::Request&lt; Result, ReplyType &gt;']]],
  ['request_3c_20replydata_20_3e_33',['Request&lt; ReplyData &gt;',['../dc/d4a/classstorages_1_1redis_1_1Request.html',1,'storages::redis']]],
  ['requestbase_34',['RequestBase',['../de/d0e/classserver_1_1request_1_1RequestBase.html',1,'server::request']]],
  ['requestcancelledexception_35',['RequestCancelledException',['../d7/d1d/classredis_1_1RequestCancelledException.html',1,'redis']]],
  ['requestcontext_36',['RequestContext',['../de/df6/classserver_1_1request_1_1RequestContext.html',1,'server::request']]],
  ['requestdatabase_37',['RequestDataBase',['../d4/ddc/classstorages_1_1redis_1_1RequestDataBase.html',1,'storages::redis']]],
  ['requestdatabase_3c_20replydata_2c_20impl_3a_3adefaultreplytype_3c_20replydata_20_3e_20_3e_38',['RequestDataBase&lt; ReplyData, impl::DefaultReplyType&lt; ReplyData &gt; &gt;',['../d4/ddc/classstorages_1_1redis_1_1RequestDataBase.html',1,'storages::redis']]],
  ['requestdatabase_3c_20result_2c_20impl_3a_3adefaultreplytype_3c_20result_20_3e_20_3e_39',['RequestDataBase&lt; Result, impl::DefaultReplyType&lt; Result &gt; &gt;',['../d4/ddc/classstorages_1_1redis_1_1RequestDataBase.html',1,'storages::redis']]],
  ['requesteval_40',['RequestEval',['../df/d69/classstorages_1_1redis_1_1RequestEval.html',1,'storages::redis']]],
  ['requestfailedexception_41',['RequestFailedException',['../dc/d8b/classredis_1_1RequestFailedException.html',1,'redis']]],
  ['requestfuture_42',['RequestFuture',['../d7/d6c/classredis_1_1RequestFuture.html',1,'redis']]],
  ['requestparseerror_43',['RequestParseError',['../d4/ddf/classserver_1_1handlers_1_1RequestParseError.html',1,'server::handlers']]],
  ['requestscandata_44',['RequestScanData',['../d7/dbd/classstorages_1_1redis_1_1RequestScanData.html',1,'storages::redis']]],
  ['requestscandatabase_45',['RequestScanDataBase',['../da/d20/classstorages_1_1redis_1_1RequestScanDataBase.html',1,'storages::redis']]],
  ['requeststats_46',['RequestStats',['../d4/d53/classclients_1_1http_1_1RequestStats.html',1,'clients::http']]],
  ['resolver_47',['Resolver',['../d0/d75/classclients_1_1dns_1_1Resolver.html',1,'clients::dns']]],
  ['resolverconfig_48',['ResolverConfig',['../dd/dc2/structclients_1_1dns_1_1ResolverConfig.html',1,'clients::dns']]],
  ['resolverexception_49',['ResolverException',['../d8/d54/classclients_1_1dns_1_1ResolverException.html',1,'clients::dns']]],
  ['resourceexhaustederror_50',['ResourceExhaustedError',['../d8/db2/classugrpc_1_1client_1_1ResourceExhaustedError.html',1,'ugrpc::client']]],
  ['resourcenotfound_51',['ResourceNotFound',['../d2/d91/classserver_1_1handlers_1_1ResourceNotFound.html',1,'server::handlers']]],
  ['response_52',['Response',['../dd/d3b/classclients_1_1http_1_1Response.html',1,'clients::http::Response'],['../d8/d24/structutest_1_1SimpleServer_1_1Response.html',1,'utest::SimpleServer::Response']]],
  ['responsebase_53',['ResponseBase',['../d3/dee/classserver_1_1request_1_1ResponseBase.html',1,'server::request']]],
  ['responsedataaccounter_54',['ResponseDataAccounter',['../d0/d6f/classserver_1_1request_1_1ResponseDataAccounter.html',1,'server::request']]],
  ['responsefuture_55',['ResponseFuture',['../d0/d9b/classclients_1_1http_1_1ResponseFuture.html',1,'clients::http']]],
  ['restrictviolation_56',['RestrictViolation',['../d9/daa/classstorages_1_1postgres_1_1RestrictViolation.html',1,'storages::postgres']]],
  ['resultset_57',['ResultSet',['../d0/d5b/classstorages_1_1postgres_1_1ResultSet.html',1,'storages::postgres']]],
  ['resultseterror_58',['ResultSetError',['../d5/d9d/classstorages_1_1postgres_1_1ResultSetError.html',1,'storages::postgres']]],
  ['resultstore_59',['ResultStore',['../d9/d54/classutils_1_1ResultStore.html',1,'utils']]],
  ['resultstore_3c_20void_20_3e_60',['ResultStore&lt; void &gt;',['../dc/db9/classutils_1_1ResultStore_3_01void_01_4.html',1,'utils']]],
  ['retryduplicatekey_61',['RetryDuplicateKey',['../d8/d28/classstorages_1_1mongo_1_1options_1_1RetryDuplicateKey.html',1,'storages::mongo::options']]],
  ['retrynilfrommaster_62',['RetryNilFromMaster',['../dd/d2d/structredis_1_1RetryNilFromMaster.html',1,'redis']]],
  ['returnnew_63',['ReturnNew',['../df/d9c/classstorages_1_1mongo_1_1options_1_1ReturnNew.html',1,'storages::mongo::options']]],
  ['reverseconstfielditerator_64',['ReverseConstFieldIterator',['../d1/d69/classstorages_1_1postgres_1_1ReverseConstFieldIterator.html',1,'storages::postgres']]],
  ['reverseconstrowiterator_65',['ReverseConstRowIterator',['../d6/d82/classstorages_1_1postgres_1_1ReverseConstRowIterator.html',1,'storages::postgres']]],
  ['rounddownroundpolicy_66',['RoundDownRoundPolicy',['../dd/d4c/classdecimal64_1_1RoundDownRoundPolicy.html',1,'decimal64']]],
  ['rounduproundpolicy_67',['RoundUpRoundPolicy',['../de/dc3/classdecimal64_1_1RoundUpRoundPolicy.html',1,'decimal64']]],
  ['row_68',['Row',['../db/dfe/classstorages_1_1postgres_1_1Row.html',1,'storages::postgres']]],
  ['rowcategory_69',['RowCategory',['../d3/d4b/structstorages_1_1postgres_1_1io_1_1traits_1_1RowCategory.html',1,'storages::postgres::io::traits']]],
  ['rowcategory_3c_3a_3autils_3a_3astrongtypedef_3c_20tag_2c_20t_2c_20ops_2c_20enable_20_3e_20_3e_70',['RowCategory&lt;::utils::StrongTypedef&lt; Tag, T, Ops, Enable &gt; &gt;',['../da/d9a/structstorages_1_1postgres_1_1io_1_1traits_1_1RowCategory_3_1_1utils_1_1StrongTypedef_3_01Tag_00a475f9e72ca0f19000d262961377c32b.html',1,'storages::postgres::io::traits']]],
  ['rowdescription_71',['RowDescription',['../d1/d9f/classstorages_1_1postgres_1_1RowDescription.html',1,'storages::postgres']]],
  ['rowindexoutofbounds_72',['RowIndexOutOfBounds',['../db/dea/classstorages_1_1postgres_1_1RowIndexOutOfBounds.html',1,'storages::postgres']]],
  ['rowsmapper_73',['RowsMapper',['../d8/d1d/classstorages_1_1clickhouse_1_1io_1_1RowsMapper.html',1,'storages::clickhouse::io']]],
  ['rowtag_74',['RowTag',['../df/d46/structstorages_1_1postgres_1_1RowTag.html',1,'storages::postgres']]],
  ['rowtype_75',['RowType',['../d4/dce/structstorages_1_1postgres_1_1io_1_1RowType.html',1,'storages::postgres::io']]],
  ['rpcerror_76',['RpcError',['../d3/d28/classugrpc_1_1client_1_1RpcError.html',1,'ugrpc::client::RpcError'],['../db/d1c/classugrpc_1_1server_1_1RpcError.html',1,'ugrpc::server::RpcError']]],
  ['rpcinterruptederror_77',['RpcInterruptedError',['../db/d86/classugrpc_1_1client_1_1RpcInterruptedError.html',1,'ugrpc::client::RpcInterruptedError'],['../d0/dd9/classugrpc_1_1server_1_1RpcInterruptedError.html',1,'ugrpc::server::RpcInterruptedError']]],
  ['runtimeerror_78',['RuntimeError',['../d6/d97/classstorages_1_1postgres_1_1RuntimeError.html',1,'storages::postgres']]]
];
