var searchData=
[
  ['rabbitendpoints_0',['RabbitEndpoints',['../dd/dba/structurabbitmq_1_1RabbitEndpoints.html',1,'urabbitmq']]],
  ['rabbitendpointsmulti_1',['RabbitEndpointsMulti',['../d3/d74/classurabbitmq_1_1RabbitEndpointsMulti.html',1,'urabbitmq']]],
  ['rabbitmq_2',['RabbitMQ',['../d5/d23/classcomponents_1_1RabbitMQ.html',1,'components']]],
  ['randombase_3',['RandomBase',['../d1/d26/classutils_1_1RandomBase.html',1,'utils']]],
  ['range_4',['Range',['../d1/df6/classstorages_1_1postgres_1_1Range.html',1,'storages::postgres']]],
  ['rate_5',['Rate',['../d2/d1b/structutils_1_1statistics_1_1Rate.html',1,'utils::statistics']]],
  ['ratecounter_6',['RateCounter',['../da/d24/classutils_1_1statistics_1_1RateCounter.html',1,'utils::statistics']]],
  ['rawcomponentbase_7',['RawComponentBase',['../d2/d86/classcomponents_1_1RawComponentBase.html',1,'components']]],
  ['rcumap_8',['RcuMap',['../d0/d1f/classrcu_1_1RcuMap.html',1,'rcu']]],
  ['rcumap_3c_20std_3a_3astring_2c_20concurrent_3a_3avariable_3c_20server_3a_3ahandlers_3a_3aauth_3a_3adigest_3a_3anonceinfo_20_3e_20_3e_9',['RcuMap&lt; std::string, concurrent::Variable&lt; server::handlers::auth::digest::NonceInfo &gt; &gt;',['../d0/d1f/classrcu_1_1RcuMap.html',1,'rcu']]],
  ['rcumap_3c_20std_3a_3astring_2c_20const_20fs_3a_3afileinfowithdata_20_3e_10',['RcuMap&lt; std::string, const fs::FileInfoWithData &gt;',['../d0/d1f/classrcu_1_1RcuMap.html',1,'rcu']]],
  ['rcumap_3c_20std_3a_3astring_2c_20logging_3a_3aloggerptr_20_3e_11',['RcuMap&lt; std::string, logging::LoggerPtr &gt;',['../d0/d1f/classrcu_1_1RcuMap.html',1,'rcu']]],
  ['rcumapiterator_12',['RcuMapIterator',['../d8/de4/classrcu_1_1RcuMapIterator.html',1,'rcu']]],
  ['readablebase_13',['ReadableBase',['../da/d1b/classengine_1_1io_1_1ReadableBase.html',1,'engine::io']]],
  ['readableptr_14',['ReadablePtr',['../dd/df3/classrcu_1_1ReadablePtr.html',1,'rcu']]],
  ['readableptr_3c_20engine_3a_3asubprocess_3a_3aenvironmentvariables_20_3e_15',['ReadablePtr&lt; engine::subprocess::EnvironmentVariables &gt;',['../dd/df3/classrcu_1_1ReadablePtr.html',1,'rcu']]],
  ['reader_16',['Reader',['../d2/d03/classdump_1_1Reader.html',1,'dump::Reader'],['../db/dd8/classugrpc_1_1server_1_1Reader.html',1,'ugrpc::server::Reader&lt; Request &gt;']]],
  ['readerwriter_17',['ReaderWriter',['../dc/db1/classugrpc_1_1server_1_1ReaderWriter.html',1,'ugrpc::server']]],
  ['readpreference_18',['ReadPreference',['../dc/db5/classstorages_1_1mongo_1_1options_1_1ReadPreference.html',1,'storages::mongo::options']]],
  ['readtableresults_19',['ReadTableResults',['../d4/d81/classydb_1_1ReadTableResults.html',1,'ydb']]],
  ['recentperiod_20',['RecentPeriod',['../d2/d67/classutils_1_1statistics_1_1RecentPeriod.html',1,'utils::statistics']]],
  ['recvfromresult_21',['RecvFromResult',['../dc/d72/structengine_1_1io_1_1Socket_1_1RecvFromResult.html',1,'engine::io::Socket']]],
  ['redis_22',['Redis',['../d6/dd0/classcomponents_1_1Redis.html',1,'components']]],
  ['rediscontrol_23',['RedisControl',['../d4/dfe/structtestsuite_1_1RedisControl.html',1,'testsuite']]],
  ['redislocal_24',['RedisLocal',['../df/d18/classstorages_1_1redis_1_1utest_1_1RedisLocal.html',1,'storages::redis::utest']]],
  ['redistest_25',['RedisTest',['../d8/d84/classstorages_1_1redis_1_1utest_1_1RedisTest.html',1,'storages::redis::utest']]],
  ['ref_26',['Ref',['../d8/d58/structchaotic_1_1Ref.html',1,'chaotic']]],
  ['refillpolicy_27',['RefillPolicy',['../de/d15/structutils_1_1TokenBucket_1_1RefillPolicy.html',1,'utils::TokenBucket']]],
  ['regex_28',['regex',['../dd/d3e/classutils_1_1regex.html',1,'utils']]],
  ['registeredntrx_29',['RegisteredNtrx',['../dc/d90/classpytest__userver_1_1plugins_1_1postgresql_1_1RegisteredNtrx.html',1,'pytest_userver::plugins::postgresql']]],
  ['registeredntrxfailuretype_30',['RegisteredNtrxFailureType',['../d3/dad/classpytest__userver_1_1plugins_1_1postgresql_1_1RegisteredNtrxFailureType.html',1,'pytest_userver::plugins::postgresql']]],
  ['registeredtrx_31',['RegisteredTrx',['../d2/dd0/classpytest__userver_1_1sql_1_1RegisteredTrx.html',1,'pytest_userver::sql']]],
  ['relaxedcounter_32',['RelaxedCounter',['../d9/d48/classutils_1_1statistics_1_1RelaxedCounter.html',1,'utils::statistics']]],
  ['relaxedcounter_3c_20size_5ft_20_3e_33',['RelaxedCounter&lt; size_t &gt;',['../d9/d48/classutils_1_1statistics_1_1RelaxedCounter.html',1,'utils::statistics']]],
  ['reliablechannel_34',['ReliableChannel',['../db/deb/classurabbitmq_1_1ReliableChannel.html',1,'urabbitmq']]],
  ['removekey_35',['RemoveKey',['../d4/de2/classpytest__userver_1_1plugins_1_1dynamic__config_1_1RemoveKey.html',1,'pytest_userver::plugins::dynamic_config']]],
  ['removetuplereferences_36',['RemoveTupleReferences',['../d1/d86/structstorages_1_1postgres_1_1io_1_1traits_1_1RemoveTupleReferences.html',1,'storages::postgres::io::traits']]],
  ['removetuplereferences_3c_20std_3a_3atuple_3c_20t_2e_2e_2e_20_3e_20_3e_37',['RemoveTupleReferences&lt; std::tuple&lt; T... &gt; &gt;',['../d7/dd1/structstorages_1_1postgres_1_1io_1_1traits_1_1RemoveTupleReferences_3_01std_1_1tuple_3_01T_8_8_8_01_4_01_4.html',1,'storages::postgres::io::traits']]],
  ['replaceone_38',['ReplaceOne',['../d4/d75/classstorages_1_1mongo_1_1bulk__ops_1_1ReplaceOne.html',1,'storages::mongo::bulk_ops::ReplaceOne'],['../d5/de4/classstorages_1_1mongo_1_1operations_1_1ReplaceOne.html',1,'storages::mongo::operations::ReplaceOne']]],
  ['reply_39',['Reply',['../d7/dc1/structdynamic__config_1_1Client_1_1Reply.html',1,'dynamic_config::Client']]],
  ['replyelemholder_40',['ReplyElemHolder',['../dc/da7/classstorages_1_1redis_1_1ScanRequest_1_1Iterator_1_1ReplyElemHolder.html',1,'storages::redis::ScanRequest::Iterator']]],
  ['request_41',['Request',['../de/df5/classclients_1_1http_1_1Request.html',1,'clients::http::Request'],['../dc/d4a/classstorages_1_1redis_1_1Request.html',1,'storages::redis::Request&lt; Result, ReplyType &gt;'],['../da/dc2/classutils_1_1statistics_1_1Request.html',1,'utils::statistics::Request']]],
  ['request_3c_20replydata_20_3e_42',['Request&lt; ReplyData &gt;',['../dc/d4a/classstorages_1_1redis_1_1Request.html',1,'storages::redis']]],
  ['requestbase_43',['RequestBase',['../de/d0e/classserver_1_1request_1_1RequestBase.html',1,'server::request']]],
  ['requestcancelledexception_44',['RequestCancelledException',['../d7/d1d/classredis_1_1RequestCancelledException.html',1,'redis']]],
  ['requestcontext_45',['RequestContext',['../de/df6/classserver_1_1request_1_1RequestContext.html',1,'server::request']]],
  ['requestdatabase_46',['RequestDataBase',['../d4/ddc/classstorages_1_1redis_1_1RequestDataBase.html',1,'storages::redis']]],
  ['requestdatabase_3c_20replydata_20_3e_47',['RequestDataBase&lt; ReplyData &gt;',['../d4/ddc/classstorages_1_1redis_1_1RequestDataBase.html',1,'storages::redis']]],
  ['requestdatabase_3c_20result_20_3e_48',['RequestDataBase&lt; Result &gt;',['../d4/ddc/classstorages_1_1redis_1_1RequestDataBase.html',1,'storages::redis']]],
  ['requesteval_49',['RequestEval',['../df/d69/classstorages_1_1redis_1_1RequestEval.html',1,'storages::redis']]],
  ['requestevalsha_50',['RequestEvalSha',['../d5/daf/classstorages_1_1redis_1_1RequestEvalSha.html',1,'storages::redis']]],
  ['requestfailedexception_51',['RequestFailedException',['../dc/d8b/classredis_1_1RequestFailedException.html',1,'redis']]],
  ['requestparseerror_52',['RequestParseError',['../d4/ddf/classserver_1_1handlers_1_1RequestParseError.html',1,'server::handlers']]],
  ['requestscandata_53',['RequestScanData',['../d7/dbd/classstorages_1_1redis_1_1RequestScanData.html',1,'storages::redis']]],
  ['requestscandatabase_54',['RequestScanDataBase',['../da/d20/classstorages_1_1redis_1_1RequestScanDataBase.html',1,'storages::redis']]],
  ['requestssource_55',['RequestsSource',['../d1/dc2/classserver_1_1congestion__control_1_1RequestsSource.html',1,'server::congestion_control']]],
  ['requesttraits_56',['RequestTraits',['../d7/d18/structutils_1_1hedging_1_1RequestTraits.html',1,'utils::hedging']]],
  ['resolver_57',['Resolver',['../d0/d75/classclients_1_1dns_1_1Resolver.html',1,'clients::dns']]],
  ['resolverconfig_58',['ResolverConfig',['../dd/dc2/structclients_1_1dns_1_1ResolverConfig.html',1,'clients::dns']]],
  ['resolverexception_59',['ResolverException',['../d8/d54/classclients_1_1dns_1_1ResolverException.html',1,'clients::dns']]],
  ['resourceexhaustederror_60',['ResourceExhaustedError',['../d8/db2/classugrpc_1_1client_1_1ResourceExhaustedError.html',1,'ugrpc::client']]],
  ['resourcenotfound_61',['ResourceNotFound',['../d2/d91/classserver_1_1handlers_1_1ResourceNotFound.html',1,'server::handlers']]],
  ['response_62',['Response',['../dd/d3b/classclients_1_1http_1_1Response.html',1,'clients::http::Response'],['../d8/d24/structutest_1_1SimpleServer_1_1Response.html',1,'utest::SimpleServer::Response']]],
  ['responsebase_63',['ResponseBase',['../d3/dee/classserver_1_1request_1_1ResponseBase.html',1,'server::request']]],
  ['responsebodystream_64',['ResponseBodyStream',['../dd/d63/classserver_1_1http_1_1ResponseBodyStream.html',1,'server::http']]],
  ['responsedataaccounter_65',['ResponseDataAccounter',['../d0/d6f/classserver_1_1request_1_1ResponseDataAccounter.html',1,'server::request']]],
  ['responsefuture_66',['ResponseFuture',['../d0/d9b/classclients_1_1http_1_1ResponseFuture.html',1,'clients::http']]],
  ['responsetruncatederror_67',['ResponseTruncatedError',['../db/dcc/classydb_1_1ResponseTruncatedError.html',1,'ydb']]],
  ['restrictviolation_68',['RestrictViolation',['../d9/daa/classstorages_1_1postgres_1_1RestrictViolation.html',1,'storages::postgres']]],
  ['result_69',['Result',['../d9/d97/classugrpc_1_1server_1_1Result.html',1,'ugrpc::server']]],
  ['resultset_70',['ResultSet',['../d0/d5b/classstorages_1_1postgres_1_1ResultSet.html',1,'storages::postgres']]],
  ['resultseterror_71',['ResultSetError',['../d5/d9d/classstorages_1_1postgres_1_1ResultSetError.html',1,'storages::postgres']]],
  ['resultstore_72',['ResultStore',['../d9/d54/classutils_1_1ResultStore.html',1,'utils']]],
  ['resultstore_3c_20void_20_3e_73',['ResultStore&lt; void &gt;',['../dc/db9/classutils_1_1ResultStore_3_01void_01_4.html',1,'utils']]],
  ['retrybudget_74',['RetryBudget',['../d5/d9f/classutils_1_1RetryBudget.html',1,'utils']]],
  ['retrybudgetsettings_75',['RetryBudgetSettings',['../d4/df0/structutils_1_1RetryBudgetSettings.html',1,'utils']]],
  ['retryduplicatekey_76',['RetryDuplicateKey',['../d8/d28/classstorages_1_1mongo_1_1options_1_1RetryDuplicateKey.html',1,'storages::mongo::options']]],
  ['retrynilfrommaster_77',['RetryNilFromMaster',['../dd/d2d/structredis_1_1RetryNilFromMaster.html',1,'redis']]],
  ['returnnew_78',['ReturnNew',['../df/d9c/classstorages_1_1mongo_1_1options_1_1ReturnNew.html',1,'storages::mongo::options']]],
  ['reverseconstfielditerator_79',['ReverseConstFieldIterator',['../d1/d69/classstorages_1_1postgres_1_1ReverseConstFieldIterator.html',1,'storages::postgres']]],
  ['reverseconstrowiterator_80',['ReverseConstRowIterator',['../d6/d82/classstorages_1_1postgres_1_1ReverseConstRowIterator.html',1,'storages::postgres']]],
  ['rounddownroundpolicy_81',['RoundDownRoundPolicy',['../dd/d4c/classdecimal64_1_1RoundDownRoundPolicy.html',1,'decimal64']]],
  ['rounduproundpolicy_82',['RoundUpRoundPolicy',['../de/dc3/classdecimal64_1_1RoundUpRoundPolicy.html',1,'decimal64']]],
  ['row_83',['Row',['../db/dfe/classstorages_1_1postgres_1_1Row.html',1,'storages::postgres::Row'],['../dc/db6/classydb_1_1Row.html',1,'ydb::Row']]],
  ['rowcategory_84',['RowCategory',['../d3/d4b/structstorages_1_1postgres_1_1io_1_1traits_1_1RowCategory.html',1,'storages::postgres::io::traits']]],
  ['rowcategory_3c_3a_3autils_3a_3astrongtypedef_3c_20tag_2c_20t_2c_20ops_2c_20enable_20_3e_20_3e_85',['RowCategory&lt;::utils::StrongTypedef&lt; Tag, T, Ops, Enable &gt; &gt;',['../da/d9a/structstorages_1_1postgres_1_1io_1_1traits_1_1RowCategory_3_1_1utils_1_1StrongTypedef_3_01Tag_00a475f9e72ca0f19000d262961377c32b.html',1,'storages::postgres::io::traits']]],
  ['rowdescription_86',['RowDescription',['../d1/d9f/classstorages_1_1postgres_1_1RowDescription.html',1,'storages::postgres']]],
  ['rowindexoutofbounds_87',['RowIndexOutOfBounds',['../db/dea/classstorages_1_1postgres_1_1RowIndexOutOfBounds.html',1,'storages::postgres']]],
  ['rowsmapper_88',['RowsMapper',['../d8/d1d/classstorages_1_1clickhouse_1_1io_1_1RowsMapper.html',1,'storages::clickhouse::io']]],
  ['rowtag_89',['RowTag',['../d6/d4d/structstorages_1_1mysql_1_1RowTag.html',1,'storages::mysql::RowTag'],['../df/d46/structstorages_1_1postgres_1_1RowTag.html',1,'storages::postgres::RowTag']]],
  ['rowtype_90',['RowType',['../d4/dce/structstorages_1_1postgres_1_1io_1_1RowType.html',1,'storages::postgres::io']]],
  ['rpccancellederror_91',['RpcCancelledError',['../d8/ddb/classugrpc_1_1client_1_1RpcCancelledError.html',1,'ugrpc::client']]],
  ['rpcerror_92',['RpcError',['../d3/d28/classugrpc_1_1client_1_1RpcError.html',1,'ugrpc::client::RpcError'],['../db/d1c/classugrpc_1_1server_1_1RpcError.html',1,'ugrpc::server::RpcError']]],
  ['rpcinterruptederror_93',['RpcInterruptedError',['../db/d86/classugrpc_1_1client_1_1RpcInterruptedError.html',1,'ugrpc::client::RpcInterruptedError'],['../d0/dd9/classugrpc_1_1server_1_1RpcInterruptedError.html',1,'ugrpc::server::RpcInterruptedError']]],
  ['runtimeerror_94',['RuntimeError',['../d6/d97/classstorages_1_1postgres_1_1RuntimeError.html',1,'storages::postgres']]],
  ['rwbase_95',['RwBase',['../d3/d1e/classengine_1_1io_1_1RwBase.html',1,'engine::io']]]
];
