var searchData=
[
  ['savepointexception_0',['SavepointException',['../dd/de3/classstorages_1_1postgres_1_1SavepointException.html',1,'storages::postgres']]],
  ['saxstream_1',['SaxStream',['../dc/db3/structformats_1_1serialize_1_1SaxStream.html',1,'formats::serialize']]],
  ['scanoptions_2',['ScanOptions',['../d5/d98/structredis_1_1ScanOptions.html',1,'redis']]],
  ['scanoptionsbase_3',['ScanOptionsBase',['../d6/d9d/classstorages_1_1redis_1_1ScanOptionsBase.html',1,'storages::redis']]],
  ['scanoptionstmpl_4',['ScanOptionsTmpl',['../d7/dfa/classstorages_1_1redis_1_1ScanOptionsTmpl.html',1,'storages::redis']]],
  ['scanreplyelem_5',['ScanReplyElem',['../d7/d19/structstorages_1_1redis_1_1ScanReplyElem.html',1,'storages::redis']]],
  ['scanreplyelem_3c_20scantag_3a_3akhscan_20_3e_6',['ScanReplyElem&lt; ScanTag::kHscan &gt;',['../db/d99/structstorages_1_1redis_1_1ScanReplyElem_3_01ScanTag_1_1kHscan_01_4.html',1,'storages::redis']]],
  ['scanreplyelem_3c_20scantag_3a_3akscan_20_3e_7',['ScanReplyElem&lt; ScanTag::kScan &gt;',['../d2/da8/structstorages_1_1redis_1_1ScanReplyElem_3_01ScanTag_1_1kScan_01_4.html',1,'storages::redis']]],
  ['scanreplyelem_3c_20scantag_3a_3aksscan_20_3e_8',['ScanReplyElem&lt; ScanTag::kSscan &gt;',['../de/dd3/structstorages_1_1redis_1_1ScanReplyElem_3_01ScanTag_1_1kSscan_01_4.html',1,'storages::redis']]],
  ['scanreplyelem_3c_20scantag_3a_3akzscan_20_3e_9',['ScanReplyElem&lt; ScanTag::kZscan &gt;',['../d6/db2/structstorages_1_1redis_1_1ScanReplyElem_3_01ScanTag_1_1kZscan_01_4.html',1,'storages::redis']]],
  ['scanrequest_10',['ScanRequest',['../d1/d52/classstorages_1_1redis_1_1ScanRequest.html',1,'storages::redis']]],
  ['schema_11',['Schema',['../d1/d3e/structyaml__config_1_1Schema.html',1,'yaml_config']]],
  ['schemaptr_12',['SchemaPtr',['../d5/d8e/classyaml__config_1_1SchemaPtr.html',1,'yaml_config']]],
  ['scopeguard_13',['ScopeGuard',['../d1/d5e/classutils_1_1ScopeGuard.html',1,'utils']]],
  ['scopetime_14',['ScopeTime',['../d9/db8/classtracing_1_1ScopeTime.html',1,'tracing']]],
  ['scopetimepause_15',['ScopeTimePause',['../d5/dd2/classutils_1_1ScopeTimePause.html',1,'utils']]],
  ['scoreoptions_16',['ScoreOptions',['../da/da1/structredis_1_1ScoreOptions.html',1,'redis']]],
  ['secdist_17',['Secdist',['../da/dc7/classcomponents_1_1Secdist.html',1,'components::Secdist'],['../d3/d3f/classstorages_1_1secdist_1_1Secdist.html',1,'storages::secdist::Secdist']]],
  ['secdistconfig_18',['SecdistConfig',['../de/d15/classstorages_1_1secdist_1_1SecdistConfig.html',1,'storages::secdist']]],
  ['secdisterror_19',['SecdistError',['../df/de2/classstorages_1_1secdist_1_1SecdistError.html',1,'storages::secdist']]],
  ['selectvalue_20',['SelectValue',['../d1/d9f/classcompiler_1_1SelectValue.html',1,'compiler']]],
  ['semaphore_21',['Semaphore',['../db/d16/classengine_1_1Semaphore.html',1,'engine']]],
  ['semaphorelock_22',['SemaphoreLock',['../d6/da6/classengine_1_1SemaphoreLock.html',1,'engine']]],
  ['sensor_23',['Sensor',['../d7/d13/classcongestion__control_1_1Sensor.html',1,'congestion_control']]],
  ['sentinel_24',['Sentinel',['../d0/de8/classredis_1_1Sentinel.html',1,'redis']]],
  ['sentinelstatistics_25',['SentinelStatistics',['../d9/dc6/structredis_1_1SentinelStatistics.html',1,'redis']]],
  ['sentinelstatisticsinternal_26',['SentinelStatisticsInternal',['../dc/d74/structredis_1_1SentinelStatisticsInternal.html',1,'redis']]],
  ['server_27',['Server',['../d0/d0b/classcomponents_1_1Server.html',1,'components::Server'],['../d0/d68/classserver_1_1Server.html',1,'server::Server'],['../d9/d55/classugrpc_1_1server_1_1Server.html',1,'ugrpc::server::Server']]],
  ['servercomponent_28',['ServerComponent',['../d7/d9a/classugrpc_1_1server_1_1ServerComponent.html',1,'ugrpc::server']]],
  ['serverconfig_29',['ServerConfig',['../dd/de2/structserver_1_1ServerConfig.html',1,'server::ServerConfig'],['../d9/d53/structugrpc_1_1server_1_1ServerConfig.html',1,'ugrpc::server::ServerConfig']]],
  ['serverconnectionerror_30',['ServerConnectionError',['../dd/d4f/classstorages_1_1postgres_1_1ServerConnectionError.html',1,'storages::postgres']]],
  ['servererror_31',['ServerError',['../da/d34/classstorages_1_1postgres_1_1ServerError.html',1,'storages::postgres']]],
  ['servererror_3c_20connectionerror_20_3e_32',['ServerError&lt; ConnectionError &gt;',['../da/d34/classstorages_1_1postgres_1_1ServerError.html',1,'storages::postgres']]],
  ['serverexception_33',['ServerException',['../d1/de8/classstorages_1_1mongo_1_1ServerException.html',1,'storages::mongo']]],
  ['serverid_34',['ServerId',['../d0/dcb/classredis_1_1ServerId.html',1,'redis']]],
  ['serveridhasher_35',['ServerIdHasher',['../d4/d77/structredis_1_1ServerIdHasher.html',1,'redis']]],
  ['servermonitor_36',['ServerMonitor',['../dc/d10/classserver_1_1handlers_1_1ServerMonitor.html',1,'server::handlers']]],
  ['servicebase_37',['ServiceBase',['../d7/d80/classugrpc_1_1server_1_1ServiceBase.html',1,'ugrpc::server']]],
  ['servicecomponentbase_38',['ServiceComponentBase',['../df/d19/classugrpc_1_1server_1_1ServiceComponentBase.html',1,'ugrpc::server']]],
  ['serviceerrorcode_39',['ServiceErrorCode',['../d7/d62/structserver_1_1handlers_1_1ServiceErrorCode.html',1,'server::handlers']]],
  ['setoptions_40',['SetOptions',['../d8/d4b/structredis_1_1SetOptions.html',1,'redis']]],
  ['settings_41',['Settings',['../d8/d85/structerror__injection_1_1Settings.html',1,'error_injection::Settings'],['../dd/d73/structstorages_1_1secdist_1_1SecdistConfig_1_1Settings.html',1,'storages::secdist::SecdistConfig::Settings'],['../dd/d99/structutils_1_1PeriodicTask_1_1Settings.html',1,'utils::PeriodicTask::Settings']]],
  ['shardstatistics_42',['ShardStatistics',['../d1/d5d/structredis_1_1ShardStatistics.html',1,'redis']]],
  ['sharedmutex_43',['SharedMutex',['../d6/d70/classengine_1_1SharedMutex.html',1,'engine']]],
  ['sharedreadableptr_44',['SharedReadablePtr',['../d2/d70/classutils_1_1SharedReadablePtr.html',1,'utils']]],
  ['sharedtaskwithresult_45',['SharedTaskWithResult',['../de/d97/classengine_1_1SharedTaskWithResult.html',1,'engine']]],
  ['signer_46',['Signer',['../d8/d17/classcrypto_1_1Signer.html',1,'crypto']]],
  ['signernone_47',['SignerNone',['../db/d35/classcrypto_1_1SignerNone.html',1,'crypto']]],
  ['signerror_48',['SignError',['../d2/deb/classcrypto_1_1SignError.html',1,'crypto']]],
  ['simpleserver_49',['SimpleServer',['../d3/d55/classutest_1_1SimpleServer.html',1,'utest']]],
  ['singleconsumerevent_50',['SingleConsumerEvent',['../d8/d87/classengine_1_1SingleConsumerEvent.html',1,'engine']]],
  ['singleconsumerside_51',['SingleConsumerSide',['../d5/d32/classconcurrent_1_1GenericQueue_1_1SingleConsumerSide.html',1,'concurrent::GenericQueue']]],
  ['singleproducerside_52',['SingleProducerSide',['../d7/d27/classconcurrent_1_1GenericQueue_1_1SingleProducerSide.html',1,'concurrent::GenericQueue']]],
  ['singlethreadedtaskprocessors_53',['SingleThreadedTaskProcessors',['../d4/dfa/classcomponents_1_1SingleThreadedTaskProcessors.html',1,'components']]],
  ['singlethreadedtaskprocessorspool_54',['SingleThreadedTaskProcessorsPool',['../df/d64/classengine_1_1SingleThreadedTaskProcessorsPool.html',1,'engine']]],
  ['singleuseevent_55',['SingleUseEvent',['../dc/dde/classengine_1_1SingleUseEvent.html',1,'engine']]],
  ['skip_56',['Skip',['../db/dc7/classstorages_1_1mongo_1_1options_1_1Skip.html',1,'storages::mongo::options']]],
  ['snapshot_57',['Snapshot',['../de/d96/classdynamic__config_1_1Snapshot.html',1,'dynamic_config']]],
  ['snapshotfailure_58',['SnapshotFailure',['../d1/da3/classstorages_1_1postgres_1_1SnapshotFailure.html',1,'storages::postgres']]],
  ['sockaddr_59',['Sockaddr',['../d1/dc0/classengine_1_1io_1_1Sockaddr.html',1,'engine::io']]],
  ['socket_60',['Socket',['../dd/dcf/classengine_1_1io_1_1Socket.html',1,'engine::io']]],
  ['sort_61',['Sort',['../da/dd2/classstorages_1_1mongo_1_1options_1_1Sort.html',1,'storages::mongo::options']]],
  ['source_62',['Source',['../d1/d22/classdynamic__config_1_1Source.html',1,'dynamic_config']]],
  ['span_63',['Span',['../d7/d1a/classtracing_1_1Span.html',1,'tracing']]],
  ['sqlroutineexception_64',['SqlRoutineException',['../d6/dcb/classstorages_1_1postgres_1_1SqlRoutineException.html',1,'storages::postgres']]],
  ['sqlstatementnotyetcomplete_65',['SqlStatementNotYetComplete',['../d4/db9/classstorages_1_1postgres_1_1SqlStatementNotYetComplete.html',1,'storages::postgres']]],
  ['sslexception_66',['SSLException',['../d8/ddc/classclients_1_1http_1_1SSLException.html',1,'clients::http']]],
  ['stacktraceguard_67',['StacktraceGuard',['../d0/d06/classlogging_1_1stacktrace__cache_1_1StacktraceGuard.html',1,'logging::stacktrace_cache']]],
  ['stat_68',['Stat',['../da/da0/structredis_1_1Stat.html',1,'redis']]],
  ['state_69',['State',['../d1/dee/classpytest__userver_1_1client_1_1State.html',1,'pytest_userver::client']]],
  ['statemanager_70',['StateManager',['../de/dbf/classpytest__userver_1_1client_1_1StateManager.html',1,'pytest_userver::client']]],
  ['statementmetricssettings_71',['StatementMetricsSettings',['../d8/d64/structstorages_1_1postgres_1_1StatementMetricsSettings.html',1,'storages::postgres']]],
  ['statistics_72',['Statistics',['../d9/de1/structclients_1_1http_1_1Statistics.html',1,'clients::http::Statistics'],['../d2/de5/structdist__lock_1_1Statistics.html',1,'dist_lock::Statistics'],['../dd/de0/classredis_1_1Statistics.html',1,'redis::Statistics']]],
  ['statisticsrequest_73',['StatisticsRequest',['../dc/dcf/structutils_1_1statistics_1_1StatisticsRequest.html',1,'utils::statistics']]],
  ['statisticsstorage_74',['StatisticsStorage',['../d8/daf/classcomponents_1_1StatisticsStorage.html',1,'components']]],
  ['stats_75',['Stats',['../d1/d55/structcongestion__control_1_1Stats.html',1,'congestion_control']]],
  ['steadyclock_76',['SteadyClock',['../d6/dac/classutils_1_1datetime_1_1SteadyClock.html',1,'utils::datetime']]],
  ['steadycoarseclock_77',['SteadyCoarseClock',['../d5/d89/structutils_1_1datetime_1_1SteadyCoarseClock.html',1,'utils::datetime']]],
  ['storage_78',['Storage',['../d5/d18/classutils_1_1statistics_1_1Storage.html',1,'utils::statistics']]],
  ['storagemock_79',['StorageMock',['../d6/dec/classdynamic__config_1_1StorageMock.html',1,'dynamic_config']]],
  ['streamingcpurelax_80',['StreamingCpuRelax',['../d7/daa/classutils_1_1StreamingCpuRelax.html',1,'utils']]],
  ['stricasecomparethreeway_81',['StrIcaseCompareThreeWay',['../d2/dcc/classutils_1_1StrIcaseCompareThreeWay.html',1,'utils']]],
  ['stricaseequal_82',['StrIcaseEqual',['../d9/ddc/classutils_1_1StrIcaseEqual.html',1,'utils']]],
  ['stricasehash_83',['StrIcaseHash',['../db/df9/classutils_1_1StrIcaseHash.html',1,'utils']]],
  ['stricaseless_84',['StrIcaseLess',['../d1/df6/classutils_1_1StrIcaseLess.html',1,'utils']]],
  ['stringbuilder_85',['StringBuilder',['../da/d55/classformats_1_1json_1_1StringBuilder.html',1,'formats::json']]],
  ['stringcolumn_86',['StringColumn',['../d1/d26/classstorages_1_1clickhouse_1_1io_1_1columns_1_1StringColumn.html',1,'storages::clickhouse::io::columns']]],
  ['stringparser_87',['StringParser',['../da/dd7/classformats_1_1json_1_1parser_1_1StringParser.html',1,'formats::json::parser']]],
  ['stringviewhash_88',['StringViewHash',['../d4/d4e/structstorages_1_1postgres_1_1utils_1_1StringViewHash.html',1,'storages::postgres::utils']]],
  ['strongtypedef_89',['StrongTypedef',['../d4/d67/classutils_1_1StrongTypedef.html',1,'utils']]],
  ['strongtypedef_3c_20class_20passwordtag_2c_20std_3a_3astring_20_3e_90',['StrongTypedef&lt; class PasswordTag, std::string &gt;',['../d4/d67/classutils_1_1StrongTypedef.html',1,'utils']]],
  ['strongtypedef_3c_20inmemoryconfig_2c_20std_3a_3astring_20_3e_91',['StrongTypedef&lt; InMemoryConfig, std::string &gt;',['../d4/d67/classutils_1_1StrongTypedef.html',1,'utils']]],
  ['subscribeclient_92',['SubscribeClient',['../d6/d2d/classstorages_1_1redis_1_1SubscribeClient.html',1,'storages::redis']]],
  ['subscriber_93',['Subscriber',['../d7/da2/classformats_1_1json_1_1parser_1_1Subscriber.html',1,'formats::json::parser']]],
  ['subscriber_3c_20bool_20_3e_94',['Subscriber&lt; bool &gt;',['../d7/da2/classformats_1_1json_1_1parser_1_1Subscriber.html',1,'formats::json::parser']]],
  ['subscriber_3c_20item_20_3e_95',['Subscriber&lt; Item &gt;',['../d7/da2/classformats_1_1json_1_1parser_1_1Subscriber.html',1,'formats::json::parser']]],
  ['subscriber_3c_20map_20_3e_96',['Subscriber&lt; Map &gt;',['../d7/da2/classformats_1_1json_1_1parser_1_1Subscriber.html',1,'formats::json::parser']]],
  ['subscriber_3c_20map_3a_3amapped_5ftype_20_3e_97',['Subscriber&lt; Map::mapped_type &gt;',['../d7/da2/classformats_1_1json_1_1parser_1_1Subscriber.html',1,'formats::json::parser']]],
  ['subscriber_3c_20number_20_3e_98',['Subscriber&lt; Number &gt;',['../d7/da2/classformats_1_1json_1_1parser_1_1Subscriber.html',1,'formats::json::parser']]],
  ['subscriber_3c_20std_3a_3aint32_5ft_20_3e_99',['Subscriber&lt; std::int32_t &gt;',['../d7/da2/classformats_1_1json_1_1parser_1_1Subscriber.html',1,'formats::json::parser']]],
  ['subscriber_3c_20std_3a_3aint64_5ft_20_3e_100',['Subscriber&lt; std::int64_t &gt;',['../d7/da2/classformats_1_1json_1_1parser_1_1Subscriber.html',1,'formats::json::parser']]],
  ['subscriber_3c_20std_3a_3aoptional_3c_20t_20_3e_20_3e_101',['Subscriber&lt; std::optional&lt; T &gt; &gt;',['../d7/da2/classformats_1_1json_1_1parser_1_1Subscriber.html',1,'formats::json::parser']]],
  ['subscriber_3c_20std_3a_3astring_20_3e_102',['Subscriber&lt; std::string &gt;',['../d7/da2/classformats_1_1json_1_1parser_1_1Subscriber.html',1,'formats::json::parser']]],
  ['subscriber_3c_20std_3a_3avector_3c_20item_20_3e_20_3e_103',['Subscriber&lt; std::vector&lt; Item &gt; &gt;',['../d7/da2/classformats_1_1json_1_1parser_1_1Subscriber.html',1,'formats::json::parser']]],
  ['subscriber_3c_20value_20_3e_104',['Subscriber&lt; Value &gt;',['../d7/da2/classformats_1_1json_1_1parser_1_1Subscriber.html',1,'formats::json::parser']]],
  ['subscribersink_105',['SubscriberSink',['../d2/dfd/classformats_1_1json_1_1parser_1_1SubscriberSink.html',1,'formats::json::parser']]],
  ['subscribersinkoptional_106',['SubscriberSinkOptional',['../d8/d1a/classformats_1_1json_1_1parser_1_1SubscriberSinkOptional.html',1,'formats::json::parser']]],
  ['subscriptiontoken_107',['SubscriptionToken',['../d3/db8/classstorages_1_1redis_1_1SubscriptionToken.html',1,'storages::redis']]],
  ['subscriptiontokenimplbase_108',['SubscriptionTokenImplBase',['../da/d4c/classstorages_1_1redis_1_1SubscriptionTokenImplBase.html',1,'storages::redis']]],
  ['suppressserverexceptions_109',['SuppressServerExceptions',['../d3/dcf/classstorages_1_1mongo_1_1options_1_1SuppressServerExceptions.html',1,'storages::mongo::options']]],
  ['swappingsmart_110',['SwappingSmart',['../d2/dbd/classutils_1_1SwappingSmart.html',1,'utils']]],
  ['swappingsmart_3c_20const_20curl_3a_3aeasy_20_3e_111',['SwappingSmart&lt; const curl::easy &gt;',['../d2/dbd/classutils_1_1SwappingSmart.html',1,'utils']]],
  ['swappingsmart_3c_20poolmap_20_3e_112',['SwappingSmart&lt; PoolMap &gt;',['../d2/dbd/classutils_1_1SwappingSmart.html',1,'utils']]],
  ['swappingsmart_3c_20redis_3a_3acommandcontrol_20_3e_113',['SwappingSmart&lt; redis::CommandControl &gt;',['../d2/dbd/classutils_1_1SwappingSmart.html',1,'utils']]],
  ['syntaxerror_114',['SyntaxError',['../d3/d71/classstorages_1_1postgres_1_1SyntaxError.html',1,'storages::postgres']]],
  ['systemerror_115',['SystemError',['../d0/d49/classstorages_1_1postgres_1_1SystemError.html',1,'storages::postgres']]],
  ['systemstatisticscollector_116',['SystemStatisticsCollector',['../df/df4/classcomponents_1_1SystemStatisticsCollector.html',1,'components']]]
];
