var searchData=
[
  ['package_20for_20ubuntu_0',['Using a prebuilt Debian package for Ubuntu',['../de/dab/md_en_2userver_2build_2build.html#autotoc_md273',1,'']]],
  ['package_20locally_1',['Building Debian package locally',['../de/dab/md_en_2userver_2build_2build.html#autotoc_md266',1,'']]],
  ['package_20maintainers_2',['Distro package maintainers',['../d1/d00/md_en_2userver_2distro__maintainers.html',1,'']]],
  ['package_20using_20docker_3',['Building Debian package using Docker',['../de/dab/md_en_2userver_2build_2build.html#autotoc_md262',1,'']]],
  ['packages_20using_20cpm_4',['Downloading packages using CPM',['../de/dab/md_en_2userver_2build_2build.html#autotoc_md255',1,'']]],
  ['packaging_20operations_5',['Packaging operations',['../d7/d65/md_en_2userver_2mongodb.html#autotoc_md737',1,'']]],
  ['page_6',['Dynamic Web Page',['../d2/d6d/md_en_2userver_2tutorial_2static__content.html#autotoc_md1241',1,'']]],
  ['page_20not_20found_7',['404: Page not Found',['../d8/dee/md_en_2userver_2404.html',1,'']]],
  ['pages_8',['Serving Static Content and Dynamic Web Pages',['../d2/d6d/md_en_2userver_2tutorial_2static__content.html',1,'']]],
  ['paging_9',['Paging',['../d7/dac/md_en_2userver_2scylladb.html#autotoc_md933',1,'Paging'],['../d2/dea/md_en_2userver_2tutorial_2scylla__service.html#autotoc_md1302',1,'Paging']]],
  ['parallel_20loading_10',['Parallel loading',['../d5/d2d/md_en_2userver_2caches.html#autotoc_md342',1,'']]],
  ['parameter_20binding_11',['Statement Preparation and Parameter Binding',['../d4/df5/md_en_2userver_2sqlite_2design__and__details.html#autotoc_md1018',1,'']]],
  ['parameterized_20test_12',['Singly-parameterized test.',['../df/d72/structutest_1_1PrintTestName.html#autotoc_md1425',1,'']]],
  ['parametrized_20test_13',['Doubly-parametrized test.',['../df/d72/structutest_1_1PrintTestName.html#autotoc_md1427',1,'']]],
  ['parametrized_20tests_20with_20custom_20names_14',['Parametrized tests with custom names',['../d4/d70/md_en_2userver_2testing.html#autotoc_md1058',1,'']]],
  ['parser_15',['JSON schema chaotic Parser',['../d8/d43/md_en_2userver_2chaotic.html#autotoc_md382',1,'']]],
  ['parsing_20could_20lead_20to_20stackoverflow_16',['CVE-2023-26224: JSON parsing could lead to StackOverflow',['../db/dde/md_en_2userver_2security__changelog.html#autotoc_md887',1,'']]],
  ['parsing_20dynamic_20configs_17',['Parsing dynamic configs',['../d5/d46/md_en_2userver_2dynamic__config.html#autotoc_md539',1,'']]],
  ['parsing_20dynamic_20configs_18',['Recommendations on parsing dynamic configs',['../d5/d46/md_en_2userver_2dynamic__config.html#autotoc_md602',1,'']]],
  ['parsing_20failure_19',['Behavior on config parsing failure',['../dd/d1a/classcomponents_1_1DynamicConfig.html#autotoc_md1471',1,'']]],
  ['parsing_20using_20utils_3a_3aregex_20',['An example of complex string parsing using &lt;span class=&quot;tt&quot;&gt;utils::regex&lt;/span&gt;',['../dd/d3e/classutils_1_1regex.html#autotoc_md1417',1,'']]],
  ['particular_20enable_20disable_20for_20service_20or_20client_21',['Particular enable/disable for service or client',['../dd/d4b/md_en_2userver_2grpc_2middlewares__toggle.html#autotoc_md375',1,'']]],
  ['party_20code_20licenses_22',['Third Party Code Licenses',['../d6/dc8/md__2data_2code_2userver_2THIRD__PARTY.html',1,'']]],
  ['passed_20and_20not_20time_5fpoint_23',['Why is &lt;span class=&quot;tt&quot;&gt;duration&lt;/span&gt; passed and not &lt;span class=&quot;tt&quot;&gt;time_point&lt;/span&gt;',['../d6/d64/md_en_2userver_2deadline__propagation.html#autotoc_md455',1,'']]],
  ['passes_20regardless_20of_20other_20fields_20set_20on_20msg_24',['Passes regardless of other fields set on msg',['../d9/d56/classtestsuite_1_1protobuf_1_1matching_1_1PartialProtobufDict.html#autotoc_md166',1,'']]],
  ['passes_20regardless_20of_20other_20fields_20set_20on_20msg_20or_20on_25',['Passes regardless of other fields set on msg or on',['../de/db3/classtestsuite_1_1protobuf_1_1matching_1_1RecursivePartialProtobufDict.html#autotoc_md167',1,'']]],
  ['path_26',['Graphite metrics by path',['../d9/dac/md_en_2userver_2service__monitor.html#autotoc_md916',1,'']]],
  ['path_20and_20prefix_20semantics_27',['6. Respect &lt;span class=&quot;tt&quot;&gt;path&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;prefix&lt;/span&gt; semantics',['../d0/d1b/md_en_2userver_2metrics__migration.html#autotoc_md811',1,'']]],
  ['path_20example_20with_20errors_20in_20the_20pipeline_28',['The call path example with errors in the pipeline',['../d7/d4b/md_en_2userver_2grpc_2server__middleware__implementation.html#autotoc_md472',1,'']]],
  ['paths_20and_20labels_20correctly_29',['3. Derive paths and labels correctly',['../d0/d1b/md_en_2userver_2metrics__migration.html#autotoc_md806',1,'']]],
  ['paths_20to_20dependencies_30',['CMake options for paths to dependencies',['../d5/d3d/md_en_2userver_2build_2options.html#autotoc_md424',1,'']]],
  ['pattern_31',['You can define matching rule out of pattern',['../de/db0/classtestsuite_1_1matching_1_1Capture.html#autotoc_md186',1,'']]],
  ['per_20call_20rpc_20hooks_20implementation_20example_32',['Per-Call (RPC) hooks implementation example',['../d7/d4b/md_en_2userver_2grpc_2server__middleware__implementation.html#autotoc_md461',1,'']]],
  ['per_20call_20rpc_20hooks_20implementation_20example_33',['Per-call (RPC) hooks implementation example',['../dc/dce/md_en_2userver_2grpc_2client__middleware__implementation.html#autotoc_md427',1,'']]],
  ['per_20client_34',['Enable middlewares per service or per client',['../dd/d4b/md_en_2userver_2grpc_2middlewares__toggle.html#autotoc_md370',1,'']]],
  ['per_20handler_20middleware_20configuration_35',['Per-handler middleware configuration',['../d6/dcc/md_en_2userver_2http__server__middlewares.html#autotoc_md608',1,'']]],
  ['per_20handler_20middleware_20pipelines_36',['Custom per-handler middleware pipelines',['../d6/dcc/md_en_2userver_2http__server__middlewares.html#autotoc_md623',1,'']]],
  ['per_20label_20metrics_37',['Usage of MonotonicByLabelStorage with a group of per-label metrics',['../dc/d4f/classutils_1_1statistics_1_1MonotonicByLabelStorage.html#autotoc_md1546',1,'']]],
  ['per_20message_20hooks_20implementation_20example_38',['Per message hooks implementation example',['../d7/d4b/md_en_2userver_2grpc_2server__middleware__implementation.html#autotoc_md465',1,'Per-message hooks implementation example'],['../dc/dce/md_en_2userver_2grpc_2client__middleware__implementation.html#autotoc_md431',1,'Per-message hooks implementation example']]],
  ['per_20query_20annotations_39',['Per-query annotations',['../d6/de0/md_en_2userver_2sql__files.html#autotoc_md1239',1,'']]],
  ['per_20service_20or_20per_20client_40',['Enable middlewares per service or per client',['../dd/d4b/md_en_2userver_2grpc_2middlewares__toggle.html#autotoc_md370',1,'']]],
  ['per_20test_41',['Changing dynamic configs in testsuite per test',['../d5/d46/md_en_2userver_2dynamic__config.html#autotoc_md691',1,'']]],
  ['performance_42',['Performance',['../d7/d08/md_en_2userver_2intro__io__bound__coro.html#autotoc_md569',1,'']]],
  ['performance_43',['performance',['../de/ddb/md_en_2userver_2driver__guide.html#autotoc_md399',1,'Easy to write, poor performance'],['../de/ddb/md_en_2userver_2driver__guide.html#autotoc_md408',1,'Hard to write, good performance'],['../de/ddb/md_en_2userver_2driver__guide.html#autotoc_md403',1,'Not too easy to write, good performance']]],
  ['performance_20considerations_44',['Performance considerations',['../d0/dc7/classconcurrent_1_1BackgroundTaskStorage.html#autotoc_md1457',1,'']]],
  ['periodic_20update_45',['testsuite-force-periodic-update',['../df/dd1/classcomponents_1_1CachingComponentBase.html#autotoc_md1437',1,'']]],
  ['periodics_20and_20distlocks_46',['Periodics and DistLocks',['../d7/dc4/md_en_2userver_2periodics.html',1,'']]],
  ['periodictask_47',['PeriodicTask',['../d7/dc4/md_en_2userver_2periodics.html#autotoc_md808',1,'']]],
  ['pgo_20clang_48',['PGO (clang)',['../d5/d3d/md_en_2userver_2build_2options.html#autotoc_md454',1,'']]],
  ['ping_49',['Ping',['../db/d69/md_en_2userver_2tutorial_2production__service.html#autotoc_md1261',1,'']]],
  ['ping_50',['ping',['../d2/db4/md_en_2components__schema_2core_2src_2server_2handlers_2ping.html',1,'']]],
  ['pipeline_51',['pipeline',['../db/df2/md_en_2userver_2grpc_2middlewares__order.html#autotoc_md379',1,'Middlewares pipeline'],['../db/d8e/md_en_2components__schema_2core_2src_2middlewares_2pipeline.html',1,'pipeline'],['../d6/dcc/md_en_2userver_2http__server__middlewares.html#autotoc_md618',1,'Server-wide middleware pipeline'],['../d7/d4b/md_en_2userver_2grpc_2server__middleware__implementation.html#autotoc_md472',1,'The call path example with errors in the pipeline']]],
  ['pipeline_5fcomponent_52',['pipeline_component',['../db/dfe/md_en_2components__schema_2core_2src_2clients_2http_2middlewares_2pipeline__component.html',1,'']]],
  ['pipelines_53',['Custom per-handler middleware pipelines',['../d6/dcc/md_en_2userver_2http__server__middlewares.html#autotoc_md623',1,'']]],
  ['pipelines_20configuration_54',['Pipelines configuration',['../d6/dcc/md_en_2userver_2http__server__middlewares.html#autotoc_md615',1,'']]],
  ['pitfalls_55',['pitfalls',['../d0/d1b/md_en_2userver_2metrics__migration.html#autotoc_md819',1,'8. Avoid missing-series pitfalls'],['../da/dd6/md_en_2userver_2cache__dumps.html#autotoc_md322',1,'Nuances and pitfalls']]],
  ['planned_20enhancements_56',['Planned Enhancements',['../d2/d5f/md_en_2userver_2mysql_2mysql__driver.html#autotoc_md746',1,'Planned Enhancements'],['../d0/db8/md_en_2userver_2kafka.html#autotoc_md758',1,'Planned Enhancements']]],
  ['platform_20specific_20build_20dependencies_57',['Platform-specific build dependencies',['../de/db9/md_en_2userver_2build_2dependencies.html#autotoc_md190',1,'']]],
  ['platforms_58',['Platforms',['../d0/dd5/md_en_2userver_2supported__platforms.html',1,'Supported Platforms'],['../d0/dd5/md_en_2userver_2supported__platforms.html#autotoc_md899',1,'Supported Platforms']]],
  ['platforms_59',['platforms',['../d5/d3d/md_en_2userver_2build_2options.html#autotoc_md416',1,'CMake options for features that are unavailable for some platforms'],['../de/db9/md_en_2userver_2build_2dependencies.html#autotoc_md202',1,'Other POSIX based platforms']]],
  ['policy_60',['Security Policy',['../de/d1b/md__2data_2code_2userver_2SECURITY.html',1,'']]],
  ['policy_61',['Cache policy',['../d4/d5f/md_en_2userver_2pg_2cache.html#pg_cc_cache_policy',1,'']]],
  ['pool_20hints_62',['OperationType and Connection Pool Hints',['../d4/df5/md_en_2userver_2sqlite_2design__and__details.html#autotoc_md1009',1,'']]],
  ['pooling_20with_20a_20postgresql_20balancer_63',['Transaction pooling with a PostgreSQL balancer',['../d7/dc1/md_en_2userver_2pg_2driver.html#autotoc_md790',1,'']]],
  ['pools_20locking_20strategy_64',['Connection pools &amp;amp; locking strategy',['../d4/df5/md_en_2userver_2sqlite_2design__and__details.html#autotoc_md999',1,'']]],
  ['poor_20performance_65',['Easy to write, poor performance',['../de/ddb/md_en_2userver_2driver__guide.html#autotoc_md399',1,'']]],
  ['portability_20testing_20in_20testsuite_66',['Metrics Portability Testing in Testsuite',['../df/d07/md_en_2userver_2functional__testing.html#autotoc_md692',1,'']]],
  ['posix_20based_20platforms_67',['Other POSIX based platforms',['../de/db9/md_en_2userver_2build_2dependencies.html#autotoc_md202',1,'']]],
  ['postfinish_68',['PreStartCall and PostFinish',['../dc/dce/md_en_2userver_2grpc_2client__middleware__implementation.html#autotoc_md423',1,'']]],
  ['postfinish_20completion_20status_69',['PostFinish completion status',['../dc/dce/md_en_2userver_2grpc_2client__middleware__implementation.html#autotoc_md426',1,'']]],
  ['postgres_70',['Deadline propagation details for Postgres',['../d6/d64/md_en_2userver_2deadline__propagation.html#autotoc_md494',1,'']]],
  ['postgres_20driver_20features_71',['Postgres driver Features',['../d7/dc1/md_en_2userver_2pg_2driver.html#autotoc_md785',1,'']]],
  ['postgres_20errors_72',['uPg: Postgres errors',['../d3/d00/md_en_2userver_2pg_2errors.html',1,'']]],
  ['postgres_5fcongestion_5fcontrol_5fsettings_73',['POSTGRES_CONGESTION_CONTROL_SETTINGS',['../d5/d3b/md_en_2dynamic__configs_2POSTGRES__CONGESTION__CONTROL__SETTINGS.html',1,'']]],
  ['postgres_5fcongestion_5fcontrol_5fsettings_20dynamic_20config_74',['POSTGRES_CONGESTION_CONTROL_SETTINGS Dynamic Config',['../d5/d3b/md_en_2dynamic__configs_2POSTGRES__CONGESTION__CONTROL__SETTINGS.html#autotoc_md139',1,'']]],
  ['postgres_5fconnection_5fpool_5fsettings_75',['POSTGRES_CONNECTION_POOL_SETTINGS',['../d0/db5/md_en_2dynamic__configs_2POSTGRES__CONNECTION__POOL__SETTINGS.html',1,'']]],
  ['postgres_5fconnection_5fpool_5fsettings_20dynamic_20config_76',['POSTGRES_CONNECTION_POOL_SETTINGS Dynamic Config',['../d0/db5/md_en_2dynamic__configs_2POSTGRES__CONNECTION__POOL__SETTINGS.html#autotoc_md145',1,'']]],
  ['postgres_5fconnection_5fsettings_77',['POSTGRES_CONNECTION_SETTINGS',['../dc/dea/md_en_2dynamic__configs_2POSTGRES__CONNECTION__SETTINGS.html',1,'']]],
  ['postgres_5fconnection_5fsettings_20dynamic_20config_78',['POSTGRES_CONNECTION_SETTINGS Dynamic Config',['../dc/dea/md_en_2dynamic__configs_2POSTGRES__CONNECTION__SETTINGS.html#autotoc_md80',1,'']]],
  ['postgres_5fconnlimit_5fmode_5fauto_5fenabled_79',['POSTGRES_CONNLIMIT_MODE_AUTO_ENABLED',['../d6/d84/md_en_2dynamic__configs_2POSTGRES__CONNLIMIT__MODE__AUTO__ENABLED.html',1,'']]],
  ['postgres_5fconnlimit_5fmode_5fauto_5fenabled_20dynamic_20config_80',['POSTGRES_CONNLIMIT_MODE_AUTO_ENABLED Dynamic Config',['../d6/d84/md_en_2dynamic__configs_2POSTGRES__CONNLIMIT__MODE__AUTO__ENABLED.html#autotoc_md78',1,'']]],
  ['postgres_5fdefault_5fcommand_5fcontrol_81',['POSTGRES_DEFAULT_COMMAND_CONTROL',['../d1/df4/md_en_2dynamic__configs_2POSTGRES__DEFAULT__COMMAND__CONTROL.html',1,'']]],
  ['postgres_5fdefault_5fcommand_5fcontrol_20dynamic_20config_82',['POSTGRES_DEFAULT_COMMAND_CONTROL Dynamic Config',['../d1/df4/md_en_2dynamic__configs_2POSTGRES__DEFAULT__COMMAND__CONTROL.html#autotoc_md79',1,'']]],
  ['postgres_5fdistlock_5fsettings_83',['POSTGRES_DISTLOCK_SETTINGS',['../dd/ddc/md_en_2dynamic__configs_2POSTGRES__DISTLOCK__SETTINGS.html',1,'']]],
  ['postgres_5fdistlock_5fsettings_20dynamic_20config_84',['POSTGRES_DISTLOCK_SETTINGS Dynamic Config',['../dd/ddc/md_en_2dynamic__configs_2POSTGRES__DISTLOCK__SETTINGS.html#autotoc_md81',1,'']]],
  ['postgres_5fhandlers_5fcommand_5fcontrol_85',['POSTGRES_HANDLERS_COMMAND_CONTROL',['../d8/d4c/md_en_2dynamic__configs_2POSTGRES__HANDLERS__COMMAND__CONTROL.html',1,'']]],
  ['postgres_5fhandlers_5fcommand_5fcontrol_20dynamic_20config_86',['POSTGRES_HANDLERS_COMMAND_CONTROL Dynamic Config',['../d8/d4c/md_en_2dynamic__configs_2POSTGRES__HANDLERS__COMMAND__CONTROL.html#autotoc_md82',1,'']]],
  ['postgres_5fqueries_5fcommand_5fcontrol_87',['POSTGRES_QUERIES_COMMAND_CONTROL',['../d4/d7a/md_en_2dynamic__configs_2POSTGRES__QUERIES__COMMAND__CONTROL.html',1,'']]],
  ['postgres_5fqueries_5fcommand_5fcontrol_20dynamic_20config_88',['POSTGRES_QUERIES_COMMAND_CONTROL Dynamic Config',['../d4/d7a/md_en_2dynamic__configs_2POSTGRES__QUERIES__COMMAND__CONTROL.html#autotoc_md85',1,'']]],
  ['postgres_5frtt_5fthreshold_5fenabled_89',['POSTGRES_RTT_THRESHOLD_ENABLED',['../d3/d99/md_en_2dynamic__configs_2POSTGRES__RTT__THRESHOLD__ENABLED.html',1,'']]],
  ['postgres_5frtt_5fthreshold_5fenabled_20dynamic_20config_90',['POSTGRES_RTT_THRESHOLD_ENABLED Dynamic Config',['../d3/d99/md_en_2dynamic__configs_2POSTGRES__RTT__THRESHOLD__ENABLED.html#autotoc_md83',1,'']]],
  ['postgres_5fstatement_5fmetrics_5fsettings_91',['POSTGRES_STATEMENT_METRICS_SETTINGS',['../d9/da1/md_en_2dynamic__configs_2POSTGRES__STATEMENT__METRICS__SETTINGS.html',1,'']]],
  ['postgres_5fstatement_5fmetrics_5fsettings_20dynamic_20config_92',['POSTGRES_STATEMENT_METRICS_SETTINGS Dynamic Config',['../d9/da1/md_en_2dynamic__configs_2POSTGRES__STATEMENT__METRICS__SETTINGS.html#autotoc_md86',1,'']]],
  ['postgres_5ftopology_5fsettings_93',['POSTGRES_TOPOLOGY_SETTINGS',['../dd/da3/md_en_2dynamic__configs_2POSTGRES__TOPOLOGY__SETTINGS.html',1,'']]],
  ['postgres_5ftopology_5fsettings_20dynamic_20config_94',['POSTGRES_TOPOLOGY_SETTINGS Dynamic Config',['../dd/da3/md_en_2dynamic__configs_2POSTGRES__TOPOLOGY__SETTINGS.html#autotoc_md140',1,'']]],
  ['postgresql_95',['PostgreSQL',['../d7/dc4/md_en_2userver_2pg_2types.html#autotoc_md861',1,'Arrays in PostgreSQL'],['../d7/dc4/md_en_2userver_2pg_2types.html#autotoc_md872',1,'Bit string types in PostgreSQL'],['../d7/dc4/md_en_2userver_2pg_2types.html#autotoc_md865',1,'C++ strong typedefs in PostgreSQL'],['../d4/d5f/md_en_2userver_2pg_2cache.html',1,'Caching Component for PostgreSQL'],['../da/d24/md_en_2userver_2tutorial_2auth__postgres.html',1,'Custom Authorization/Authentication via PostgreSQL'],['../d6/d31/md_en_2userver_2tutorial_2digest__auth__postgres.html',1,'Digest Authorization/Authentication via PostgreSQL'],['../d7/dc4/md_en_2userver_2pg_2types.html#autotoc_md868',1,'Geometry types in PostgreSQL'],['../d7/dc4/md_en_2userver_2pg_2types.html#autotoc_md857',1,'How not to get skewed times in the PostgreSQL'],['../d7/dc4/md_en_2userver_2pg_2types.html#autotoc_md860',1,'JSON and JSONB in PostgreSQL'],['../d7/dc4/md_en_2userver_2pg_2types.html#autotoc_md871',1,'Network types in PostgreSQL'],['../de/d6a/md_en_2index.html#autotoc_md123',1,'PostgreSQL'],['../d5/da0/md_en_2userver_2pg_2user__types.html#autotoc_md893',1,'Time Range and Other Widely Used Types in PostgreSQL']]],
  ['postgresql_20→_20c_20type_20mapping_96',['PostgreSQL → C++ type mapping',['../d6/de0/md_en_2userver_2sql__files.html#autotoc_md1202',1,'']]],
  ['postgresql_20and_20locally_20differ_20for_20multiple_20hours_20minutes_97',['PostgreSQL: Timestamp in PostgreSQL and locally differ for multiple hours/minutes',['../de/d61/md_en_2userver_2faq.html#autotoc_md683',1,'']]],
  ['postgresql_20balancer_98',['Transaction pooling with a PostgreSQL balancer',['../d7/dc1/md_en_2userver_2pg_2driver.html#autotoc_md790',1,'']]],
  ['postgresql_20bytea_20support_99',['PostgreSQL bytea support',['../d7/dc4/md_en_2userver_2pg_2types.html#autotoc_md870',1,'']]],
  ['postgresql_20cache_100',['PostgreSQL Cache',['../da/d24/md_en_2userver_2tutorial_2auth__postgres.html#autotoc_md985',1,'']]],
  ['postgresql_20domain_20user_20type_101',['Mapping a C++ type to PostgreSQL domain user type',['../d5/da0/md_en_2userver_2pg_2user__types.html#autotoc_md873',1,'']]],
  ['postgresql_20dto_20codegen_102',['PostgreSQL DTO codegen',['../d6/de0/md_en_2userver_2sql__files.html#autotoc_md1123',1,'']]],
  ['postgresql_20enum_20type_103',['Mapping a C++ enum to PostgreSQL enum type',['../d5/da0/md_en_2userver_2pg_2user__types.html#autotoc_md881',1,'']]],
  ['postgresql_20license_104',['PostgreSQL License',['../d6/dc8/md__2data_2code_2userver_2THIRD__PARTY.html#autotoc_md65',1,'']]],
  ['postgresql_20ranges_105',['PostgreSQL ranges',['../d7/dc4/md_en_2userver_2pg_2types.html#autotoc_md867',1,'']]],
  ['postgresql_20results_106',['uPg: Typed PostgreSQL results',['../d5/d53/md_en_2userver_2pg_2user__row__types.html',1,'']]],
  ['postgresql_20service_107',['PostgreSQL service',['../d4/d31/md_en_2userver_2tutorial_2postgres__service.html',1,'']]],
  ['postgresql_20table_108',['PostgreSQL Table',['../d6/d31/md_en_2userver_2tutorial_2digest__auth__postgres.html#autotoc_md965',1,'']]],
  ['postgresql_20text_109',['Mapping C++ enums to PostgreSQL text',['../d5/da0/md_en_2userver_2pg_2user__types.html#autotoc_md886',1,'']]],
  ['postgresql_20types_110',['PostgreSQL types',['../d7/dc4/md_en_2userver_2pg_2types.html#autotoc_md839',1,'Fundamental PostgreSQL types'],['../d7/dc4/md_en_2userver_2pg_2types.html#autotoc_md864',1,'User-defined PostgreSQL types']]],
  ['postgresql_20types_20not_20covered_20above_111',['PostgreSQL types not covered above',['../d7/dc4/md_en_2userver_2pg_2types.html#autotoc_md874',1,'']]],
  ['postgresql_20user_20type_20mappings_112',['uPg: PostgreSQL user type mappings',['../d5/da0/md_en_2userver_2pg_2user__types.html',1,'']]],
  ['postgresql_20versions_113',['PostgreSQL versions',['../de/db9/md_en_2userver_2build_2dependencies.html#autotoc_md203',1,'']]],
  ['postgresql_3a_20something_20is_20slow_114',['PostgreSQL: Something is slow',['../de/d61/md_en_2userver_2faq.html#autotoc_md680',1,'']]],
  ['postgresql_3a_20statement_20xxxx_20network_20timeout_20error_115',['PostgreSQL: Statement XXXX network timeout error',['../de/d61/md_en_2userver_2faq.html#autotoc_md675',1,'']]],
  ['postgresql_3a_20statement_20xxxx_20was_20canceled_116',['PostgreSQL: Statement XXXX was canceled',['../de/d61/md_en_2userver_2faq.html#autotoc_md678',1,'']]],
  ['postgresql_3a_20timestamp_20in_20postgresql_20and_20locally_20differ_20for_20multiple_20hours_20minutes_117',['PostgreSQL: Timestamp in PostgreSQL and locally differ for multiple hours/minutes',['../de/d61/md_en_2userver_2faq.html#autotoc_md683',1,'']]],
  ['postrecvmessage_118',['PreSendMessage and PostRecvMessage',['../dc/dce/md_en_2userver_2grpc_2client__middleware__implementation.html#autotoc_md428',1,'']]],
  ['postrecvmessage_20and_20presendmessage_119',['PostRecvMessage and PreSendMessage',['../d7/d4b/md_en_2userver_2grpc_2server__middleware__implementation.html#autotoc_md463',1,'']]],
  ['pprof_20protocol_120',['Usage of the &lt;span class=&quot;tt&quot;&gt;pprof&lt;/span&gt; protocol',['../d2/d34/classserver_1_1handlers_1_1Jemalloc.html#autotoc_md1525',1,'']]],
  ['pr_121',['Issue, feature and pull requests (PR)',['../d0/d7b/md_en_2userver_2development_2releases.html#autotoc_md348',1,'']]],
  ['practices_122',['Production configs and best practices',['../db/d69/md_en_2userver_2tutorial_2production__service.html',1,'']]],
  ['pre_20announce_20may_20jul_202022_123',['Pre announce (May-Jul 2022)',['../dd/d6f/md_en_2userver_2roadmap__and__changelog__v1.html#autotoc_md1381',1,'']]],
  ['pre_20caching_20data_20from_20http_20remote_124',['Pre-caching data from HTTP remote',['../dc/d8a/md_en_2userver_2tutorial_2http__caching.html',1,'']]],
  ['prebuilt_20debian_20package_20for_20ubuntu_125',['Using a prebuilt Debian package for Ubuntu',['../de/dab/md_en_2userver_2build_2build.html#autotoc_md273',1,'']]],
  ['precedence_20rules_20of_20dynamic_20config_20modification_20in_20testsuite_126',['Precedence rules of dynamic config modification in testsuite',['../d5/d46/md_en_2userver_2dynamic__config.html#autotoc_md701',1,'']]],
  ['predefined_20roles_127',['Predefined roles',['../d1/d92/classcomponents_1_1Postgres.html#autotoc_md39',1,'']]],
  ['prefix_128',['Prometheus metrics by prefix',['../d9/dac/md_en_2userver_2service__monitor.html#autotoc_md913',1,'']]],
  ['prefix_20semantics_129',['6. Respect &lt;span class=&quot;tt&quot;&gt;path&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;prefix&lt;/span&gt; semantics',['../d0/d1b/md_en_2userver_2metrics__migration.html#autotoc_md811',1,'']]],
  ['prefixes_20and_20labels_130',['9. Use &lt;span class=&quot;tt&quot;&gt;sliced()&lt;/span&gt; to remove repeated prefixes and labels',['../d0/d1b/md_en_2userver_2metrics__migration.html#autotoc_md820',1,'']]],
  ['preparation_20and_20parameter_20binding_131',['Statement Preparation and Parameter Binding',['../d4/df5/md_en_2userver_2sqlite_2design__and__details.html#autotoc_md1018',1,'']]],
  ['preparations_132',['Preparations',['../d5/db9/md_en_2userver_2tutorial_2grpc__middleware__service.html#autotoc_md1047',1,'Preparations'],['../d6/daa/md_en_2userver_2tutorial_2grpc__service.html#autotoc_md1141',1,'Preparations'],['../d6/daa/md_en_2userver_2tutorial_2grpc__service.html#autotoc_md1164',1,'Preparations']]],
  ['presendmessage_133',['PostRecvMessage and PreSendMessage',['../d7/d4b/md_en_2userver_2grpc_2server__middleware__implementation.html#autotoc_md463',1,'']]],
  ['presendmessage_20and_20postrecvmessage_134',['PreSendMessage and PostRecvMessage',['../dc/dce/md_en_2userver_2grpc_2client__middleware__implementation.html#autotoc_md428',1,'']]],
  ['prestartcall_20and_20postfinish_135',['PreStartCall and PostFinish',['../dc/dce/md_en_2userver_2grpc_2client__middleware__implementation.html#autotoc_md423',1,'']]],
  ['pretty_20printers_136',['Custom pretty-printers',['../d2/d1b/md_en_2userver_2gdb__debugging.html#autotoc_md432',1,'']]],
  ['pretty_20printers_20and_20commands_137',['Adding new pretty-printers and commands',['../d2/d1b/md_en_2userver_2gdb__debugging.html#autotoc_md447',1,'']]],
  ['primitives_138',['Primitives',['../d1/d9a/md_en_2userver_2metrics.html#autotoc_md687',1,'Additional Primitives'],['../d6/d6c/md_en_2userver_2synchronization.html#autotoc_md1071',1,'Cancellations, Cancellation Blockers and Synchronization Primitives'],['../d6/d6c/md_en_2userver_2synchronization.html',1,'Synchronization Primitives']]],
  ['primitives_139',['primitives',['../d0/dd8/md_en_2userver_2lru__cache.html#autotoc_md599',1,'Low level primitives'],['../d6/d6c/md_en_2userver_2synchronization.html#autotoc_md1077',1,'Synchronization mechanisms and primitives']]],
  ['primitives_20for_20metrics_140',['Basic Primitives for Metrics',['../d1/d9a/md_en_2userver_2metrics.html#autotoc_md676',1,'']]],
  ['printers_141',['Custom pretty-printers',['../d2/d1b/md_en_2userver_2gdb__debugging.html#autotoc_md432',1,'']]],
  ['printers_20and_20commands_142',['Adding new pretty-printers and commands',['../d2/d1b/md_en_2userver_2gdb__debugging.html#autotoc_md447',1,'']]],
  ['process_20all_20the_20remaining_20items_20during_20shutdown_143',['Using queue closing mechanic to process all the remaining items during shutdown',['../d6/d6c/md_en_2userver_2synchronization.html#autotoc_md1143',1,'']]],
  ['process_5fstarter_144',['process_starter',['../d1/d30/md_en_2components__schema_2core_2src_2components_2process__starter.html',1,'']]],
  ['processor_145',['processor',['../db/d90/md_en_2userver_2task__processors__guide.html#autotoc_md956',1,'fs-task-processor'],['../db/d90/md_en_2userver_2task__processors__guide.html#autotoc_md952',1,'main-task-processor'],['../db/d90/md_en_2userver_2task__processors__guide.html#autotoc_md958',1,'monitor-task-processor'],['../db/d90/md_en_2userver_2task__processors__guide.html#autotoc_md959',1,'Moving CPU-bound tasks to a separate task processor']]],
  ['processors_146',['Common Task Processors',['../db/d90/md_en_2userver_2task__processors__guide.html#autotoc_md951',1,'']]],
  ['processors_147',['processors',['../db/d90/md_en_2userver_2task__processors__guide.html#autotoc_md957',1,'single-threaded-task-processors'],['../db/d69/md_en_2userver_2tutorial_2production__service.html#autotoc_md1242',1,'Task processors']]],
  ['processsocket_148',['ProcessSocket',['../dc/d93/md_en_2userver_2tutorial_2tcp__service.html#autotoc_md1209',1,'ProcessSocket'],['../db/db9/md_en_2userver_2tutorial_2tcp__full.html#autotoc_md1268',1,'ProcessSocket']]],
  ['produce_20message_20on_20http_20request_149',['Produce message on HTTP request',['../d9/d1c/md_en_2userver_2tutorial_2kafka__service.html#autotoc_md1155',1,'']]],
  ['produce_20messages_20to_20topic_150',['Produce messages to topic',['../d9/d1c/md_en_2userver_2tutorial_2kafka__service.html#autotoc_md1150',1,'']]],
  ['producer_20declaration_151',['HTTP handler component (producer) declaration',['../d9/d1c/md_en_2userver_2tutorial_2kafka__service.html#autotoc_md1146',1,'']]],
  ['producer_20features_152',['Producer Features',['../d0/db8/md_en_2userver_2kafka.html#autotoc_md751',1,'']]],
  ['producer_5fcomponent_153',['producer_component',['../d8/d9c/md_en_2components__schema_2kafka_2src_2kafka_2producer__component.html',1,'']]],
  ['producers_154',['Using queue closing mechanic to stop the producers',['../d6/d6c/md_en_2userver_2synchronization.html#autotoc_md1148',1,'']]],
  ['production_20configs_20and_20best_20practices_155',['Production configs and best practices',['../db/d69/md_en_2userver_2tutorial_2production__service.html',1,'']]],
  ['production_20service_156',['production service',['../db/d69/md_en_2userver_2tutorial_2production__service.html#autotoc_md1274',1,'Dynamic configs of a sample production service'],['../d4/d1a/md_en_2userver_2memory__profile__running__service.html',1,'Memory profiling a production service']]],
  ['production_20setup_20with_20balancer_157',['Production setup with balancer',['../d2/d58/md_en_2userver_2deploy__env.html#autotoc_md338',1,'']]],
  ['production_20setup_20with_20service_20mesh_158',['Production setup with service-mesh',['../d2/d58/md_en_2userver_2deploy__env.html#autotoc_md355',1,'']]],
  ['production_20use_159',['Is userver ready for production use?',['../d0/d7b/md_en_2userver_2development_2releases.html#autotoc_md336',1,'']]],
  ['profile_20a_20running_20service_160',['How to profile a running service',['../d4/d1a/md_en_2userver_2memory__profile__running__service.html#autotoc_md551',1,'']]],
  ['profile_20a_20service_161',['How to profile a service',['../db/d8f/md_en_2userver_2profile__context__switches.html#autotoc_md848',1,'']]],
  ['profile_20at_20service_20start_162',['How to profile at service start',['../d4/d1a/md_en_2userver_2memory__profile__running__service.html#autotoc_md553',1,'']]],
  ['profiles_163',['What to search in profiles',['../db/d8f/md_en_2userver_2profile__context__switches.html#autotoc_md851',1,'']]],
  ['profiling_20a_20production_20service_164',['Memory profiling a production service',['../d4/d1a/md_en_2userver_2memory__profile__running__service.html',1,'']]],
  ['profiling_20context_20switches_165',['Profiling context switches',['../db/d8f/md_en_2userver_2profile__context__switches.html',1,'']]],
  ['project_166',['Creating a new service project',['../de/dab/md_en_2userver_2build_2build.html#autotoc_md247',1,'']]],
  ['projects_167',['Use userver in your projects',['../de/dab/md_en_2userver_2build_2build.html#autotoc_md269',1,'']]],
  ['prometheus_20graphite_20and_20default_20metrics_20description_168',['Retrieving Service Statistics and Metrics (Prometheus/Graphite/...) and Default Metrics Description',['../d9/dac/md_en_2userver_2service__monitor.html',1,'']]],
  ['prometheus_20metrics_20by_20prefix_169',['Prometheus metrics by prefix',['../d9/dac/md_en_2userver_2service__monitor.html#autotoc_md913',1,'']]],
  ['propagation_170',['propagation',['../d6/d64/md_en_2userver_2deadline__propagation.html#autotoc_md446',1,'A classic example of deadline propagation'],['../d6/d64/md_en_2userver_2deadline__propagation.html#autotoc_md464',1,'Blocking the deadline propagation'],['../d6/d64/md_en_2userver_2deadline__propagation.html',1,'Deadline propagation']]],
  ['propagation_20details_20for_20grpc_20clients_171',['Deadline propagation details for gRPC clients',['../d6/d64/md_en_2userver_2deadline__propagation.html#autotoc_md487',1,'']]],
  ['propagation_20details_20for_20grpc_20service_20implementations_172',['Deadline propagation details for gRPC service implementations',['../d6/d64/md_en_2userver_2deadline__propagation.html#autotoc_md473',1,'']]],
  ['propagation_20details_20for_20http_20handlers_173',['Deadline propagation details for HTTP handlers',['../d6/d64/md_en_2userver_2deadline__propagation.html#autotoc_md466',1,'']]],
  ['propagation_20details_20for_20mongo_174',['Deadline propagation details for Mongo',['../d6/d64/md_en_2userver_2deadline__propagation.html#autotoc_md491',1,'']]],
  ['propagation_20details_20for_20postgres_175',['Deadline propagation details for Postgres',['../d6/d64/md_en_2userver_2deadline__propagation.html#autotoc_md494',1,'']]],
  ['propagation_20details_20for_20redis_176',['Deadline propagation details for Redis',['../d6/d64/md_en_2userver_2deadline__propagation.html#autotoc_md495',1,'']]],
  ['propagation_20details_20for_20the_20http_20client_177',['Deadline propagation details for the HTTP client',['../d6/d64/md_en_2userver_2deadline__propagation.html#autotoc_md482',1,'']]],
  ['propagation_20http_20headers_178',['Deadline Propagation HTTP headers',['../d6/d64/md_en_2userver_2deadline__propagation.html#autotoc_md457',1,'']]],
  ['propagation_20work_179',['Why doesn&apos;t &quot;close propagation&quot; work',['../d6/d64/md_en_2userver_2deadline__propagation.html#autotoc_md449',1,'']]],
  ['protocol_180',['protocol',['../df/d0c/md_en_2userver_2logging.html#autotoc_md926',1,'OpenTelemetry protocol'],['../d2/d34/classserver_1_1handlers_1_1Jemalloc.html#autotoc_md1525',1,'Usage of the &lt;span class=&quot;tt&quot;&gt;pprof&lt;/span&gt; protocol']]],
  ['protocols_181',['Protocols',['../de/d6a/md_en_2index.html#autotoc_md120',1,'']]],
  ['prototyping_182',['Easy - library for single file prototyping',['../da/de8/md_en_2userver_2libraries_2easy.html',1,'']]],
  ['provided_183',['Guarantees provided',['../d7/dc4/md_en_2userver_2periodics.html#autotoc_md816',1,'']]],
  ['provider_5fcomponent_184',['provider_component',['../d9/d5c/md_en_2components__schema_2core_2src_2storages_2secdist_2provider__component.html',1,'']]],
  ['proxy_185',['Proxy',['../df/d37/md_en_2userver_2chaotic__clients.html#autotoc_md282',1,'']]],
  ['public_20disclosure_20timing_186',['Public Disclosure Timing',['../de/d1b/md__2data_2code_2userver_2SECURITY.html#autotoc_md67',1,'']]],
  ['publications_20and_20videos_187',['Publications and Videos',['../dc/d30/md_en_2userver_2publications.html',1,'']]],
  ['pull_20requests_188',['Releases, Trunk-based Development and Pull Requests',['../d0/d7b/md_en_2userver_2development_2releases.html',1,'']]],
  ['pull_20requests_20pr_189',['Issue, feature and pull requests (PR)',['../d0/d7b/md_en_2userver_2development_2releases.html#autotoc_md348',1,'']]],
  ['put_190',['PUT',['../dd/dea/classserver_1_1handlers_1_1DynamicDebugLog.html#autotoc_md1515',1,'']]],
  ['pytest_5fuserver_191',['pytest_userver',['../df/d07/md_en_2userver_2functional__testing.html#autotoc_md586',1,'']]],
  ['python_20environment_192',['Python environment',['../df/d07/md_en_2userver_2functional__testing.html#autotoc_md541',1,'']]]
];
