var searchData=
[
  ['a_20c_20enum_20to_20postgresql_20enum_20type_0',['Mapping a C++ enum to PostgreSQL enum type',['../d5/da0/md_en_2userver_2pg_2user__types.html#autotoc_md898',1,'']]],
  ['a_20c_20type_20to_20postgresql_20domain_20user_20type_1',['Mapping a C++ type to PostgreSQL domain user type',['../d5/da0/md_en_2userver_2pg_2user__types.html#autotoc_md890',1,'']]],
  ['a_20cache_2',['Writing a cache',['../d5/d2d/md_en_2userver_2caches.html#autotoc_md253',1,'']]],
  ['a_20cancelled_20task_3',['Lifetime of a cancelled task',['../d8/d00/md_en_2userver_2intro.html#autotoc_md721',1,'']]],
  ['a_20classic_20example_20of_20deadline_20propagation_4',['A classic example of deadline propagation',['../d6/d64/md_en_2userver_2deadline__propagation.html#autotoc_md430',1,'']]],
  ['a_20composite_20row_20user_20type_5',['Mapping a composite (row) user type',['../d5/da0/md_en_2userver_2pg_2user__types.html#autotoc_md892',1,'']]],
  ['a_20composite_20type_20and_20an_20enum_6',['Example 1: a composite type and an enum',['../d6/de0/md_en_2userver_2sql__files.html#autotoc_md1188',1,'']]],
  ['a_20dynamic_20config_7',['What is needed to define a dynamic config',['../d5/d46/md_en_2userver_2dynamic__config.html#autotoc_md519',1,'']]],
  ['a_20group_20of_20per_20label_20metrics_8',['Usage of MonotonicByLabelStorage with a group of per-label metrics',['../dc/d4f/classutils_1_1statistics_1_1MonotonicByLabelStorage.html#autotoc_md1540',1,'']]],
  ['a_20light_20client_20factory_20used_20to_20deliver_20dynamic_20configs_20to_20the_20service_20itself_9',['Example: a &quot;light&quot; client factory used to deliver dynamic configs to the service itself',['../db/d02/classugrpc_1_1client_1_1ClientFactoryComponent.html#autotoc_md1601',1,'']]],
  ['a_20look_20at_20the_20core_20dump_20or_20stacktrace_10',['Hint: Take a look at the core dump or stacktrace.',['../de/d61/md_en_2userver_2faq.html#autotoc_md391',1,'']]],
  ['a_20look_20at_20the_20metrics_11',['Hint: Take a look at the metrics',['../de/d61/md_en_2userver_2faq.html#autotoc_md403',1,'']]],
  ['a_20look_20at_20the_20service_20logs_12',['a look at the service logs',['../de/d61/md_en_2userver_2faq.html#autotoc_md389',1,'Hint: Take a look at the service logs'],['../de/d61/md_en_2userver_2faq.html#autotoc_md394',1,'Hint: Take a look at the service logs']]],
  ['a_20middleware_13',['a middleware',['../de/d6a/md_en_2userver_2grpc_2client__middlewares.html#autotoc_md321',1,'Static config options of a middleware'],['../da/de9/md_en_2userver_2grpc_2server__middlewares.html#autotoc_md461',1,'Static config options of a middleware'],['../da/da2/md_en_2userver_2grpc_2middlewares__configuration.html#autotoc_md417',1,'Yaml config for a middleware']]],
  ['a_20multiconsumerevent_20after_20waking_20up_14',['Destroying a MultiConsumerEvent after waking up',['../d9/d31/classengine_1_1MultiConsumerEvent.html#autotoc_md1479',1,'']]],
  ['a_20new_20component_20or_20class_20would_20be_20enough_15',['Should I write a new component or class would be enough?',['../dc/dcc/md_en_2userver_2component__system.html#autotoc_md335',1,'']]],
  ['a_20new_20service_20project_16',['Creating a new service project',['../de/dab/md_en_2userver_2build_2build.html#autotoc_md366',1,'']]],
  ['a_20postgresql_20balancer_17',['Transaction pooling with a PostgreSQL balancer',['../d7/dc1/md_en_2userver_2pg_2driver.html#autotoc_md748',1,'']]],
  ['a_20prebuilt_20debian_20package_20for_20ubuntu_18',['Using a prebuilt Debian package for Ubuntu',['../de/dab/md_en_2userver_2build_2build.html#autotoc_md418',1,'']]],
  ['a_20production_20service_19',['Memory profiling a production service',['../d4/d1a/md_en_2userver_2memory__profile__running__service.html',1,'']]],
  ['a_20query_20with_20annotations_20',['Example 3: a query with annotations',['../d6/de0/md_en_2userver_2sql__files.html#autotoc_md1216',1,'']]],
  ['a_20running_20service_21',['a running service',['../de/d61/md_en_2userver_2faq.html#autotoc_md401',1,'Hint: Grab a stacktrace from a running service'],['../d4/d1a/md_en_2userver_2memory__profile__running__service.html#autotoc_md612',1,'How to profile a running service']]],
  ['a_20sample_20production_20service_22',['Dynamic configs of a sample production service',['../db/d69/md_en_2userver_2tutorial_2production__service.html#autotoc_md1299',1,'']]],
  ['a_20separate_20task_20processor_23',['Moving CPU-bound tasks to a separate task processor',['../db/d90/md_en_2userver_2task__processors__guide.html#autotoc_md1007',1,'']]],
  ['a_20service_24',['How to profile a service',['../db/d8f/md_en_2userver_2profile__context__switches.html#autotoc_md844',1,'']]],
  ['a_20service_20template_25',['a service template',['../da/de8/md_en_2userver_2libraries_2easy.html#autotoc_md653',1,'Migration from the easy library to a service template'],['../da/de8/md_en_2userver_2libraries_2easy.html#autotoc_md668',1,'Migration of code from the easy library to a service template'],['../da/de8/md_en_2userver_2libraries_2easy.html#autotoc_md660',1,'Migration of configs from the easy library to a service template'],['../da/de8/md_en_2userver_2libraries_2easy.html#autotoc_md662',1,'Migration of database schema from the easy library to a service template']]],
  ['a_20service_20with_20the_20easy_20library_26',['Custom and multiple dependencies for a service with the easy library',['../da/de8/md_en_2userver_2libraries_2easy.html#autotoc_md645',1,'']]],
  ['a_20simple_20select_20query_27',['Example 2: a simple SELECT query',['../d6/de0/md_en_2userver_2sql__files.html#autotoc_md1198',1,'']]],
  ['a_20singleuseevent_20after_20waking_20up_28',['Destroying a SingleUseEvent after waking up',['../dc/dde/classengine_1_1SingleUseEvent.html#autotoc_md1482',1,'']]],
  ['a_20span_29',['Creating a Span',['../df/d0c/md_en_2userver_2logging.html#autotoc_md861',1,'']]],
  ['a_20stacktrace_20from_20a_20running_20service_30',['Hint: Grab a stacktrace from a running service',['../de/d61/md_en_2userver_2faq.html#autotoc_md401',1,'']]],
  ['a_20string_31',['order_id must be a string',['../de/d52/classtestsuite_1_1matching_1_1IsInstance.html#autotoc_md146',1,'']]],
  ['a_20subset_20of_20tests_32',['Changing dynamic configs in testsuite for a subset of tests',['../d5/d46/md_en_2userver_2dynamic__config.html#autotoc_md593',1,'']]],
  ['a_20task_33',['Ways to cancel a task',['../d8/d00/md_en_2userver_2intro.html#autotoc_md696',1,'']]],
  ['a_20test_20name_34',['Another option to override a test name.',['../df/d72/structutest_1_1PrintTestName.html#autotoc_md1420',1,'']]],
  ['a_20vulnerability_35',['a Vulnerability',['../de/d1b/md__2data_2code_2userver_2SECURITY.html#autotoc_md141',1,'Reporting a Vulnerability'],['../de/d1b/md__2data_2code_2userver_2SECURITY.html#autotoc_md143',1,'When Should I NOT Report a Vulnerability?'],['../de/d1b/md__2data_2code_2userver_2SECURITY.html#autotoc_md142',1,'When Should I Report a Vulnerability?']]],
  ['abi_20stability_36',['ABI stability',['../db/d57/md_en_2userver_2development_2stability.html#autotoc_md273',1,'']]],
  ['abi_20stability_20versioning_37',['API and ABI stability, versioning',['../db/d57/md_en_2userver_2development_2stability.html',1,'']]],
  ['aborted_20sigsegv_20what_20to_20do_38',['Service Terminated/Aborted/SIGSEGV. What to do?',['../de/d61/md_en_2userver_2faq.html#autotoc_md388',1,'']]],
  ['about_20this_20specific_20overload_39',['About this specific overload',['../dc/db7/group__userver__concurrency.html#autotoc_md23',1,'']]],
  ['above_40',['PostgreSQL types not covered above',['../d7/dc4/md_en_2userver_2pg_2types.html#autotoc_md900',1,'']]],
  ['abs_20num_2010_41',['match integers abs(num) &amp;gt;= 10',['../de/d63/classtestsuite_1_1matching_1_1Or.html#autotoc_md149',1,'']]],
  ['acceptable_20here_42',['int or float is acceptable here',['../de/d52/classtestsuite_1_1matching_1_1IsInstance.html#autotoc_md147',1,'']]],
  ['access_20synchronization_20versioning_20memory_20consumption_43',['Access synchronization, versioning, memory consumption',['../d5/d2d/md_en_2userver_2caches.html#autotoc_md246',1,'']]],
  ['activation_20troubleshooting_44',['Mongo Congestion Control Activation Troubleshooting',['../d7/d65/md_en_2userver_2mongodb.html#autotoc_md705',1,'']]],
  ['adding_20and_20using_20your_20own_20dynamic_20configs_45',['Adding and using your own dynamic configs',['../d5/d46/md_en_2userver_2dynamic__config.html#autotoc_md517',1,'']]],
  ['adding_20new_20pretty_20printers_20and_20commands_46',['Adding new pretty-printers and commands',['../d2/d1b/md_en_2userver_2gdb__debugging.html#autotoc_md470',1,'']]],
  ['additional_20information_3a_47',['Additional information:',['../de/dab/md_en_2userver_2build_2build.html#autotoc_md407',1,'']]],
  ['additional_20loggers_48',['Additional loggers',['../df/d0c/md_en_2userver_2logging.html#autotoc_md843',1,'']]],
  ['additional_20primitives_49',['Additional Primitives',['../d1/d9a/md_en_2userver_2metrics.html#autotoc_md769',1,'']]],
  ['additional_20userver_20libraries_20in_20service_20templates_50',['Using additional userver libraries in service templates',['../de/dab/md_en_2userver_2build_2build.html#autotoc_md369',1,'']]],
  ['after_51',['Before/After',['../db/df2/md_en_2userver_2grpc_2middlewares__order.html#autotoc_md506',1,'']]],
  ['after_20assertions_52',['7. Use &lt;span class=&quot;tt&quot;&gt;metrics_diff()&lt;/span&gt; for before/after assertions',['../d0/d1b/md_en_2userver_2metrics__migration.html#autotoc_md852',1,'']]],
  ['after_20waking_20up_53',['after waking up',['../d9/d31/classengine_1_1MultiConsumerEvent.html#autotoc_md1479',1,'Destroying a MultiConsumerEvent after waking up'],['../dc/dde/classengine_1_1SingleUseEvent.html#autotoc_md1482',1,'Destroying a SingleUseEvent after waking up']]],
  ['aka_20timepointtz_20and_20timepointwithouttz_54',['Timestamp Support aka TimePointTz and TimePointWithoutTz',['../d7/dc4/md_en_2userver_2pg_2types.html#autotoc_md886',1,'']]],
  ['alerts_55',['Alerts',['../db/d69/md_en_2userver_2tutorial_2production__service.html#autotoc_md1312',1,'']]],
  ['all_20in_20one_20single_20instance_20setup_56',['All-in-one single instance setup',['../d2/d58/md_en_2userver_2deploy__env.html#autotoc_md347',1,'']]],
  ['all_20middlewares_57',['How to disable all middlewares',['../dd/d4b/md_en_2userver_2grpc_2middlewares__toggle.html#autotoc_md452',1,'']]],
  ['all_20the_20dns_20records_58',['Rediscover all the DNS records',['../dc/d72/md_en_2userver_2dns__control.html#autotoc_md311',1,'']]],
  ['all_20the_20remaining_20items_20during_20shutdown_59',['Using queue closing mechanic to process all the remaining items during shutdown',['../d6/d6c/md_en_2userver_2synchronization.html#autotoc_md1155',1,'']]],
  ['allof_60',['JSON schema allOf',['../d8/d43/md_en_2userver_2chaotic.html#autotoc_md367',1,'']]],
  ['allowed_20arguments_61',['Allowed arguments',['../d7/d7f/classserver_1_1handlers_1_1CustomHandlerException.html#autotoc_md1502',1,'']]],
  ['alpine_62',['Alpine',['../de/db9/md_en_2userver_2build_2dependencies.html#autotoc_md209',1,'']]],
  ['alpine_63',['alpine',['../db/d4c/md_en_2deps_2alpine.html',1,'']]],
  ['amqp_200_209_201_64',['RabbitMQ (AMQP 0-9-1)',['../d7/d90/md_en_2userver_2rabbitmq__driver.html',1,'']]],
  ['an_20enum_65',['Example 1: a composite type and an enum',['../d6/de0/md_en_2userver_2sql__files.html#autotoc_md1188',1,'']]],
  ['an_20example_20of_20complex_20string_20parsing_20using_20utils_3a_3aregex_66',['An example of complex string parsing using &lt;span class=&quot;tt&quot;&gt;utils::regex&lt;/span&gt;',['../dd/d3e/classutils_1_1regex.html#autotoc_md1411',1,'']]],
  ['analyse_20the_20dump_67',['How to analyse the dump',['../d4/d1a/md_en_2userver_2memory__profile__running__service.html#autotoc_md616',1,'']]],
  ['analyse_20the_20dump_20without_20the_20service_20binary_68',['How to analyse the dump without the service binary',['../d4/d1a/md_en_2userver_2memory__profile__running__service.html#autotoc_md619',1,'']]],
  ['and_20abi_20stability_20versioning_69',['API and ABI stability, versioning',['../db/d57/md_en_2userver_2development_2stability.html',1,'']]],
  ['and_20an_20enum_70',['Example 1: a composite type and an enum',['../d6/de0/md_en_2userver_2sql__files.html#autotoc_md1188',1,'']]],
  ['and_20benchmarking_71',['Testing and Benchmarking',['../de/d6a/md_en_2index.html#autotoc_md122',1,'']]],
  ['and_20benchmarks_72',['Unit Tests and Benchmarks',['../d4/d70/md_en_2userver_2testing.html',1,'']]],
  ['and_20benchmarks_73',['and benchmarks',['../df/d35/md_en_2userver_2build_2userver.html',1,'Build instructions for userver&apos;s own samples, tests and benchmarks'],['../d7/d7a/md_en_2userver_2grpc_2grpc.html#autotoc_md801',1,'Unit tests and benchmarks'],['../d5/d46/md_en_2userver_2dynamic__config.html#autotoc_md588',1,'Using dynamic config in unit tests and benchmarks']]],
  ['and_20best_20practices_74',['Production configs and best practices',['../db/d69/md_en_2userver_2tutorial_2production__service.html',1,'']]],
  ['and_20changelog_75',['Roadmap and Changelog',['../da/d9a/md_en_2userver_2roadmap__and__changelog.html',1,'']]],
  ['and_20changelog_20v1_20and_20earlier_76',['Roadmap and Changelog (v1 and earlier)',['../dd/d6f/md_en_2userver_2roadmap__and__changelog__v1.html',1,'']]],
  ['and_20client_77',['Functional testing for the sample gRPC service and client',['../d6/daa/md_en_2userver_2tutorial_2grpc__service.html#autotoc_md1126',1,'']]],
  ['and_20client_20gtest_78',['Unit testing for the sample gRPC service and client (gtest)',['../d6/daa/md_en_2userver_2tutorial_2grpc__service.html#autotoc_md1165',1,'']]],
  ['and_20commands_79',['Adding new pretty-printers and commands',['../d2/d1b/md_en_2userver_2gdb__debugging.html#autotoc_md470',1,'']]],
  ['and_20component_20hooks_80',['Service lifetime stages and component hooks',['../dc/dcc/md_en_2userver_2component__system.html#autotoc_md319',1,'']]],
  ['and_20configuration_81',['Usage and configuration',['../d6/dcc/md_en_2userver_2http__server__middlewares.html#autotoc_md576',1,'']]],
  ['and_20connection_20pool_20hints_82',['OperationType and Connection Pool Hints',['../d4/df5/md_en_2userver_2sqlite_2design__and__details.html#autotoc_md958',1,'']]],
  ['and_20coroutines_83',['I/O-bound Applications and Coroutines',['../d7/d08/md_en_2userver_2intro__io__bound__coro.html',1,'']]],
  ['and_20cpp_20files_20from_20jsonschema_84',['Use generated .hpp and .cpp files from JSONSchema',['../d8/d43/md_en_2userver_2chaotic.html#autotoc_md315',1,'']]],
  ['and_20create_20our_20own_20ugrpc_20retries_85',['Why we decided to move away from grpc-core retries for unary calls and create our own ugrpc retries',['../d8/d54/md_en_2userver_2grpc_2timeouts__retries.html#autotoc_md725',1,'']]],
  ['and_20deadlines_86',['Command control and deadlines',['../dd/d07/md_en_2userver_2odbc.html#autotoc_md907',1,'']]],
  ['and_20default_20metrics_20description_87',['Retrieving Service Statistics and Metrics (Prometheus/Graphite/...) and Default Metrics Description',['../d9/dac/md_en_2userver_2service__monitor.html',1,'']]],
  ['and_20delete_88',['KeyValueHandler::Patch and Delete',['../d2/dea/md_en_2userver_2tutorial_2scylla__service.html#autotoc_md1289',1,'']]],
  ['and_20destruction_20order_89',['Components construction and destruction order',['../dc/dcc/md_en_2userver_2component__system.html#autotoc_md320',1,'']]],
  ['and_20distlocks_90',['Periodics and DistLocks',['../d7/dc4/md_en_2userver_2periodics.html',1,'']]],
  ['and_20dynamic_20web_20pages_91',['Serving Static Content and Dynamic Web Pages',['../d2/d6d/md_en_2userver_2tutorial_2static__content.html',1,'']]],
  ['and_20earlier_92',['Roadmap and Changelog (v1 and earlier)',['../dd/d6f/md_en_2userver_2roadmap__and__changelog__v1.html',1,'']]],
  ['and_20embedding_20files_93',['userver_embed_file and embedding files',['../da/d92/md_en_2userver_2codegen__overview.html#autotoc_md183',1,'']]],
  ['and_20errors_20in_20middlewares_94',['and errors in middlewares',['../dc/dce/md_en_2userver_2grpc_2client__middleware__implementation.html#autotoc_md442',1,'Exceptions and errors in middlewares'],['../d7/d4b/md_en_2userver_2grpc_2server__middleware__implementation.html#autotoc_md558',1,'Exceptions and errors in middlewares']]],
  ['and_20expirable_20lru_20caches_95',['Least Recently Used (LRU) Caches and expirable LRU caches',['../d0/dd8/md_en_2userver_2lru__cache.html',1,'']]],
  ['and_20friends_96',['and friends',['../d6/d6c/md_en_2userver_2synchronization.html#autotoc_md1135',1,'concurrent::MpscQueue and friends'],['../d6/d6c/md_en_2userver_2synchronization.html#autotoc_md1124',1,'engine::WaitAny and friends']]],
  ['and_20functional_20testing_97',['Unit and functional testing',['../d0/db8/md_en_2userver_2kafka.html#autotoc_md570',1,'']]],
  ['and_20grpc_20core_20retry_20capabilities_98',['Comparison of userver-grpc and grpc-core retry capabilities',['../d8/d54/md_en_2userver_2grpc_2timeouts__retries.html#autotoc_md707',1,'']]],
  ['and_20gtest_99',['How to test metrics in testsuite and gtest',['../d1/d9a/md_en_2userver_2metrics.html#autotoc_md782',1,'']]],
  ['and_20implementation_20details_100',['and implementation details',['../dd/d32/md_en_2userver_2mysql_2design__and__details.html',1,'MySQL driver design and implementation details'],['../d4/df5/md_en_2userver_2sqlite_2design__and__details.html',1,'SQLite driver design and implementation details']]],
  ['and_20install_101',['Configure, Build and Install',['../de/dab/md_en_2userver_2build_2build.html',1,'']]],
  ['and_20labels_102',['9. Use &lt;span class=&quot;tt&quot;&gt;sliced()&lt;/span&gt; to remove repeated prefixes and labels',['../d0/d1b/md_en_2userver_2metrics__migration.html#autotoc_md869',1,'']]],
  ['and_20labels_20correctly_103',['3. Derive paths and labels correctly',['../d0/d1b/md_en_2userver_2metrics__migration.html#autotoc_md829',1,'']]],
  ['and_20lifetime_20of_20clients_104',['References from components and lifetime of clients',['../dc/dcc/md_en_2userver_2component__system.html#autotoc_md322',1,'']]],
  ['and_20locally_20differ_20for_20multiple_20hours_20minutes_105',['PostgreSQL: Timestamp in PostgreSQL and locally differ for multiple hours/minutes',['../de/d61/md_en_2userver_2faq.html#autotoc_md416',1,'']]],
  ['and_20logging_106',['Span hierarchy and logging',['../df/d0c/md_en_2userver_2logging.html#autotoc_md857',1,'']]],
  ['and_20management_107',['Fun and Management',['../dc/d30/md_en_2userver_2publications.html#autotoc_md884',1,'']]],
  ['and_20metrics_108',['Statistics and Metrics',['../d1/d9a/md_en_2userver_2metrics.html',1,'']]],
  ['and_20metrics_109',['Dynamic configuration and metrics',['../dd/d07/md_en_2userver_2odbc.html#autotoc_md912',1,'']]],
  ['and_20metrics_20prometheus_20graphite_20and_20default_20metrics_20description_110',['Retrieving Service Statistics and Metrics (Prometheus/Graphite/...) and Default Metrics Description',['../d9/dac/md_en_2userver_2service__monitor.html',1,'']]],
  ['and_20monitoring_111',['Stack usage: overflows and monitoring',['../d7/dc8/md_en_2userver_2stack.html#autotoc_md952',1,'']]],
  ['and_20multipart_20form_20data_20testing_112',['File uploads and multipart/form-data testing',['../df/d0f/md_en_2userver_2tutorial_2multipart__service.html',1,'']]],
  ['and_20multiple_20dependencies_20for_20a_20service_20with_20the_20easy_20library_113',['Custom and multiple dependencies for a service with the easy library',['../da/de8/md_en_2userver_2libraries_2easy.html#autotoc_md645',1,'']]],
  ['and_20not_20time_5fpoint_114',['Why is &lt;span class=&quot;tt&quot;&gt;duration&lt;/span&gt; passed and not &lt;span class=&quot;tt&quot;&gt;time_point&lt;/span&gt;',['../d6/d64/md_en_2userver_2deadline__propagation.html#autotoc_md437',1,'']]],
  ['and_20objectives_115',['Design Challenges and Objectives',['../d4/df5/md_en_2userver_2sqlite_2design__and__details.html#autotoc_md953',1,'']]],
  ['and_20oncallfinish_116',['and OnCallFinish',['../d7/d4b/md_en_2userver_2grpc_2server__middleware__implementation.html#autotoc_md561',1,'Errors and OnCallFinish'],['../d7/d4b/md_en_2userver_2grpc_2server__middleware__implementation.html#autotoc_md549',1,'OnCallStart and OnCallFinish']]],
  ['and_20other_20i_20o_20bound_20applications_117',['Microservices and other I/O-bound applications',['../d7/d08/md_en_2userver_2intro__io__bound__coro.html#autotoc_md615',1,'']]],
  ['and_20other_20widely_20used_20types_20in_20postgresql_118',['Time Range and Other Widely Used Types in PostgreSQL',['../d5/da0/md_en_2userver_2pg_2user__types.html#autotoc_md906',1,'']]],
  ['and_20parameter_20binding_119',['Statement Preparation and Parameter Binding',['../d4/df5/md_en_2userver_2sqlite_2design__and__details.html#autotoc_md961',1,'']]],
  ['and_20pitfalls_120',['Nuances and pitfalls',['../da/dd6/md_en_2userver_2cache__dumps.html#autotoc_md288',1,'']]],
  ['and_20postfinish_121',['PreStartCall and PostFinish',['../dc/dce/md_en_2userver_2grpc_2client__middleware__implementation.html#autotoc_md429',1,'']]],
  ['and_20postrecvmessage_122',['PreSendMessage and PostRecvMessage',['../dc/dce/md_en_2userver_2grpc_2client__middleware__implementation.html#autotoc_md436',1,'']]],
  ['and_20prefix_20semantics_123',['6. Respect &lt;span class=&quot;tt&quot;&gt;path&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;prefix&lt;/span&gt; semantics',['../d0/d1b/md_en_2userver_2metrics__migration.html#autotoc_md847',1,'']]],
  ['and_20presendmessage_124',['PostRecvMessage and PreSendMessage',['../d7/d4b/md_en_2userver_2grpc_2server__middleware__implementation.html#autotoc_md555',1,'']]],
  ['and_20primitives_125',['Synchronization mechanisms and primitives',['../d6/d6c/md_en_2userver_2synchronization.html#autotoc_md1096',1,'']]],
  ['and_20pull_20requests_126',['Releases, Trunk-based Development and Pull Requests',['../d0/d7b/md_en_2userver_2development_2releases.html',1,'']]],
  ['and_20pull_20requests_20pr_127',['Issue, feature and pull requests (PR)',['../d0/d7b/md_en_2userver_2development_2releases.html#autotoc_md270',1,'']]],
  ['and_20release_20model_128',['Releases and Release model',['../d0/d7b/md_en_2userver_2development_2releases.html#autotoc_md260',1,'']]],
  ['and_20requests_129',['HTTP Flatbuf handler and requests',['../d8/d91/md_en_2userver_2tutorial_2flatbuf__service.html',1,'']]],
  ['and_20responses_130',['Limit log length of the requests and responses',['../df/d0c/md_en_2userver_2logging.html#autotoc_md822',1,'']]],
  ['and_20retries_131',['gRPC Timeouts and Retries',['../d8/d54/md_en_2userver_2grpc_2timeouts__retries.html',1,'']]],
  ['and_20run_132',['and Run',['../d8/d91/md_en_2userver_2tutorial_2flatbuf__service.html#autotoc_md973',1,'Build and Run'],['../d2/dfc/md_en_2userver_2tutorial_2json__to__yaml.html#autotoc_md1009',1,'Build and Run'],['../d4/d95/md_en_2userver_2tutorial_2config__service.html#autotoc_md1025',1,'Build and Run'],['../d5/db9/md_en_2userver_2tutorial_2grpc__middleware__service.html#autotoc_md1048',1,'Build and Run'],['../d5/d81/md_en_2userver_2tutorial_2mongo__service.html#autotoc_md1067',1,'Build and Run'],['../da/d16/md_en_2userver_2tutorial_2hello__service.html#autotoc_md1075',1,'Build and Run'],['../da/d24/md_en_2userver_2tutorial_2auth__postgres.html#autotoc_md1087',1,'Build and Run'],['../df/d0f/md_en_2userver_2tutorial_2multipart__service.html#autotoc_md1134',1,'Build and Run'],['../de/d05/md_en_2userver_2tutorial_2websocket__client.html#autotoc_md1212',1,'Build and Run'],['../d7/d9e/md_en_2userver_2tutorial_2websocket__service.html#autotoc_md1213',1,'Build and Run'],['../d6/daa/md_en_2userver_2tutorial_2grpc__service.html#autotoc_md1119',1,'Build and Run'],['../dc/d93/md_en_2userver_2tutorial_2tcp__service.html#autotoc_md1231',1,'Build and Run'],['../d3/da2/md_en_2userver_2tutorial_2redis__service.html#autotoc_md1176',1,'Build and Run'],['../dc/d8a/md_en_2userver_2tutorial_2http__caching.html#autotoc_md1167',1,'Build and Run'],['../d2/d6d/md_en_2userver_2tutorial_2static__content.html#autotoc_md1204',1,'Build and Run'],['../db/db9/md_en_2userver_2tutorial_2tcp__full.html#autotoc_md1249',1,'Build and Run'],['../d4/d31/md_en_2userver_2tutorial_2postgres__service.html#autotoc_md1296',1,'Build and Run'],['../d0/d68/md_en_2userver_2tutorial_2ydb__topic__writer__service.html#autotoc_md1333',1,'Build and Run'],['../d2/dea/md_en_2userver_2tutorial_2scylla__service.html#autotoc_md1311',1,'Build and Run'],['../d9/d0b/md_en_2userver_2tutorial_2ydb__service.html#autotoc_md1348',1,'Build and Run']]],
  ['and_20run_133',['Build and run',['../d9/d1c/md_en_2userver_2tutorial_2kafka__service.html#autotoc_md1301',1,'']]],
  ['and_20savepoints_134',['Transactions and Savepoints',['../d4/df5/md_en_2userver_2sqlite_2design__and__details.html#autotoc_md964',1,'']]],
  ['and_20schema_20init_135',['Raw CQL and schema init',['../d2/dea/md_en_2userver_2tutorial_2scylla__service.html#autotoc_md1303',1,'']]],
  ['and_20scope_136',['Motivation and scope',['../d4/df5/md_en_2userver_2sqlite_2design__and__details.html#autotoc_md951',1,'']]],
  ['and_20service_137',['gRPC client and service',['../d6/daa/md_en_2userver_2tutorial_2grpc__service.html',1,'']]],
  ['and_20spans_138',['TCP full-duplex server with metrics and Spans',['../db/db9/md_en_2userver_2tutorial_2tcp__full.html',1,'']]],
  ['and_20statistics_139',['How to write metrics and statistics',['../d1/d9a/md_en_2userver_2metrics.html#autotoc_md745',1,'']]],
  ['and_20statistics_20of_20userver_140',['Existing Metrics and Statistics of userver',['../d1/d9a/md_en_2userver_2metrics.html#autotoc_md744',1,'']]],
  ['and_20subset_20label_20matching_20deliberately_141',['5. Use exact and subset label matching deliberately',['../d0/d1b/md_en_2userver_2metrics__migration.html#autotoc_md840',1,'']]],
  ['and_20supported_20versions_142',['Scope and Supported Versions',['../de/d1b/md__2data_2code_2userver_2SECURITY.html#autotoc_md139',1,'']]],
  ['and_20synchronization_20primitives_143',['Cancellations, Cancellation Blockers and Synchronization Primitives',['../d6/d6c/md_en_2userver_2synchronization.html#autotoc_md1089',1,'']]],
  ['and_20telegram_20support_20chats_144',['Community and Telegram Support chats',['../de/d6a/md_en_2index.html#autotoc_md115',1,'']]],
  ['and_20templates_145',['Helper services and templates',['../d0/dd5/md_en_2userver_2supported__platforms.html#autotoc_md928',1,'']]],
  ['and_20testing_146',['Usage and testing',['../da/dc5/md_en_2userver_2libraries_2s3api.html#autotoc_md491',1,'']]],
  ['and_20timepointwithouttz_147',['Timestamp Support aka TimePointTz and TimePointWithoutTz',['../d7/dc4/md_en_2userver_2pg_2types.html#autotoc_md886',1,'']]],
  ['and_20tracing_148',['and Tracing',['../df/d0c/md_en_2userver_2logging.html',1,'Logging and Tracing'],['../df/d0c/md_en_2userver_2logging.html#autotoc_md878',1,'Separate Sinks for Logs and Tracing']]],
  ['and_20using_20your_20own_20dynamic_20configs_149',['Adding and using your own dynamic configs',['../d5/d46/md_en_2userver_2dynamic__config.html#autotoc_md517',1,'']]],
  ['and_20videos_150',['Publications and Videos',['../dc/d30/md_en_2userver_2publications.html',1,'']]],
  ['and_20x_20yatraceid_151',['Linking service requests via X-YaRequestId, X-YaSpanId and X-YaTraceId',['../df/d0c/md_en_2userver_2logging.html#autotoc_md863',1,'']]],
  ['annotations_152',['annotations',['../d6/de0/md_en_2userver_2sql__files.html#autotoc_md1216',1,'Example 3: a query with annotations'],['../d6/de0/md_en_2userver_2sql__files.html#autotoc_md1267',1,'Per-query annotations']]],
  ['announce_20may_20jul_202022_153',['Pre announce (May-Jul 2022)',['../dd/d6f/md_en_2userver_2roadmap__and__changelog__v1.html#autotoc_md1375',1,'']]],
  ['announcements_154',['Announcements',['../dc/d30/md_en_2userver_2publications.html#autotoc_md865',1,'Announcements'],['../de/d1b/md__2data_2code_2userver_2SECURITY.html#autotoc_md138',1,'Security Announcements']]],
  ['another_20option_20to_20override_20a_20test_20name_155',['Another option to override a test name.',['../df/d72/structutest_1_1PrintTestName.html#autotoc_md1420',1,'']]],
  ['apache_202_200_20license_156',['Apache-2.0 License',['../d6/dc8/md__2data_2code_2userver_2THIRD__PARTY.html#autotoc_md193',1,'']]],
  ['apache_20kafka_157',['Apache Kafka',['../d0/db8/md_en_2userver_2kafka.html',1,'Apache Kafka'],['../de/d6a/md_en_2index.html#autotoc_md128',1,'Apache Kafka']]],
  ['api_158',['API',['../d6/d64/md_en_2userver_2deadline__propagation.html#autotoc_md451',1,'API'],['../d7/d7a/md_en_2userver_2grpc_2grpc.html#autotoc_md794',1,'Generic API'],['../d0/d1b/md_en_2userver_2metrics__migration.html',1,'Migrating tests from the removed legacy metrics API'],['../da/dc5/md_en_2userver_2libraries_2s3api.html',1,'S3 API'],['../df/d94/md_en_2userver_2http__server.html#autotoc_md501',1,'Streaming API']]],
  ['api_20and_20abi_20stability_20versioning_159',['API and ABI stability, versioning',['../db/d57/md_en_2userver_2development_2stability.html',1,'']]],
  ['api_20stability_160',['API stability',['../db/d57/md_en_2userver_2development_2stability.html#autotoc_md267',1,'']]],
  ['application_20logic_161',['Application Logic',['../da/d16/md_en_2userver_2tutorial_2hello__service.html#autotoc_md1046',1,'Application Logic'],['../d2/d6d/md_en_2userver_2tutorial_2static__content.html#autotoc_md1142',1,'Application Logic']]],
  ['applications_162',['Microservices and other I/O-bound applications',['../d7/d08/md_en_2userver_2intro__io__bound__coro.html#autotoc_md615',1,'']]],
  ['applications_20and_20coroutines_163',['I/O-bound Applications and Coroutines',['../d7/d08/md_en_2userver_2intro__io__bound__coro.html',1,'']]],
  ['april_202023_164',['Beta (April 2023)',['../dd/d6f/md_en_2userver_2roadmap__and__changelog__v1.html#autotoc_md1366',1,'']]],
  ['april_202024_165',['April 2024',['../dd/d6f/md_en_2userver_2roadmap__and__changelog__v1.html#autotoc_md1353',1,'']]],
  ['arch_166',['arch',['../d1/d94/md_en_2deps_2arch.html',1,'']]],
  ['arch_20manjaro_167',['Arch, Manjaro',['../de/db9/md_en_2userver_2build_2dependencies.html#autotoc_md211',1,'']]],
  ['architectural_20overview_168',['Architectural Overview',['../d4/df5/md_en_2userver_2sqlite_2design__and__details.html#autotoc_md954',1,'']]],
  ['architecture_169',['Driver Architecture',['../dd/d32/md_en_2userver_2mysql_2design__and__details.html#autotoc_md750',1,'']]],
  ['are_20cancelled_20before_20they_20start_20running_170',['What happens to tasks that are cancelled before they start running',['../d8/d00/md_en_2userver_2intro.html#autotoc_md716',1,'']]],
  ['are_20metrics_171',['What are Metrics?',['../d1/d9a/md_en_2userver_2metrics.html#autotoc_md735',1,'']]],
  ['are_20unavailable_20for_20some_20platforms_172',['CMake options for features that are unavailable for some platforms',['../d5/d3d/md_en_2userver_2build_2options.html#autotoc_md313',1,'']]],
  ['arguments_173',['Arguments',['../dc/db7/group__userver__concurrency.html#autotoc_md25',1,'']]],
  ['arguments_174',['arguments',['../d7/d7f/classserver_1_1handlers_1_1CustomHandlerException.html#autotoc_md1502',1,'Allowed arguments'],['../df/d07/md_en_2userver_2functional__testing.html#autotoc_md610',1,'userver_testsuite_add() arguments']]],
  ['array_175',['JSON schema type: array',['../d8/d43/md_en_2userver_2chaotic.html#autotoc_md346',1,'']]],
  ['arrays_20in_20postgresql_176',['Arrays in PostgreSQL',['../d7/dc4/md_en_2userver_2pg_2types.html#autotoc_md889',1,'']]],
  ['as_20long_20as_20the_20listed_20fields_20match_177',['msg.nested_field, as long as the listed fields match.',['../de/db3/classtestsuite_1_1protobuf_1_1matching_1_1RecursivePartialProtobufDict.html#autotoc_md158',1,'']]],
  ['as_20the_20listed_20fields_20match_178',['msg.nested_field, as long as the listed fields match.',['../de/db3/classtestsuite_1_1protobuf_1_1matching_1_1RecursivePartialProtobufDict.html#autotoc_md158',1,'']]],
  ['asked_20questions_179',['Frequently Asked Questions',['../de/d61/md_en_2userver_2faq.html',1,'']]],
  ['assertions_180',['assertions',['../d0/d1b/md_en_2userver_2metrics__migration.html#autotoc_md852',1,'7. Use &lt;span class=&quot;tt&quot;&gt;metrics_diff()&lt;/span&gt; for before/after assertions'],['../d4/d70/md_en_2userver_2testing.html#autotoc_md1004',1,'Exception assertions'],['../d4/d70/md_en_2userver_2testing.html#autotoc_md1010',1,'Exception assertions']]],
  ['assertions_20compact_181',['11. Keep metrics assertions compact',['../d0/d1b/md_en_2userver_2metrics__migration.html#autotoc_md877',1,'']]],
  ['async_182',['Flavors of Async',['../d8/d00/md_en_2userver_2intro.html#autotoc_md656',1,'']]],
  ['async_20model_183',['Async Model',['../d4/df5/md_en_2userver_2sqlite_2design__and__details.html#autotoc_md963',1,'']]],
  ['asynchronous_20framework_184',['The C++ Asynchronous Framework',['../de/d6a/md_en_2index.html',1,'']]],
  ['at_20runtime_185',['at runtime',['../d1/de2/md_en_2userver_2log__level__running__service.html#autotoc_md636',1,'Changing the log level at runtime'],['../d1/de2/md_en_2userver_2log__level__running__service.html',1,'Logging at runtime']]],
  ['at_20runtime_3a_186',['Building the query at runtime:',['../d2/d39/classcomponents_1_1MongoCache.html#autotoc_md1550',1,'']]],
  ['at_20service_20start_187',['How to profile at service start',['../d4/d1a/md_en_2userver_2memory__profile__running__service.html#autotoc_md614',1,'']]],
  ['at_20the_20core_20dump_20or_20stacktrace_188',['Hint: Take a look at the core dump or stacktrace.',['../de/d61/md_en_2userver_2faq.html#autotoc_md391',1,'']]],
  ['at_20the_20metrics_189',['Hint: Take a look at the metrics',['../de/d61/md_en_2userver_2faq.html#autotoc_md403',1,'']]],
  ['at_20the_20service_20logs_190',['at the service logs',['../de/d61/md_en_2userver_2faq.html#autotoc_md389',1,'Hint: Take a look at the service logs'],['../de/d61/md_en_2userver_2faq.html#autotoc_md394',1,'Hint: Take a look at the service logs']]],
  ['august_202022_191',['Beta (August 2022)',['../dd/d6f/md_en_2userver_2roadmap__and__changelog__v1.html#autotoc_md1374',1,'']]],
  ['august_202023_192',['Beta (August 2023)',['../dd/d6f/md_en_2userver_2roadmap__and__changelog__v1.html#autotoc_md1362',1,'']]],
  ['auth_20checker_20testing_193',['Auth checker testing',['../de/d97/classserver_1_1handlers_1_1ImplicitOptions.html#autotoc_md1513',1,'']]],
  ['auth_5fchecker_5fsettings_5fcomponent_194',['auth_checker_settings_component',['../de/d6b/md_en_2components__schema_2core_2src_2server_2handlers_2auth_2auth__checker__settings__component.html',1,'auth_checker_settings_component'],['../df/ddb/md_en_2components__schema_2core_2src_2server_2handlers_2auth_2digest_2auth__checker__settings__component.html',1,'auth_checker_settings_component']]],
  ['authentication_195',['Authentication',['../df/d37/md_en_2userver_2chaotic__clients.html#autotoc_md232',1,'Authentication'],['../d4/dcc/md_en_2userver_2chaotic__handlers.html#autotoc_md224',1,'Authentication'],['../db/d02/classugrpc_1_1client_1_1ClientFactoryComponent.html#autotoc_md1598',1,'Authentication'],['../df/d37/md_en_2userver_2chaotic__clients.html#autotoc_md233',1,'HTTP Digest Authentication']]],
  ['authentication_20via_20postgresql_196',['Authentication via PostgreSQL',['../da/d24/md_en_2userver_2tutorial_2auth__postgres.html',1,'Custom Authorization/Authentication via PostgreSQL'],['../d6/d31/md_en_2userver_2tutorial_2digest__auth__postgres.html',1,'Digest Authorization/Authentication via PostgreSQL']]],
  ['authorization_20authentication_20via_20postgresql_197',['Authorization Authentication via PostgreSQL',['../da/d24/md_en_2userver_2tutorial_2auth__postgres.html',1,'Custom Authorization/Authentication via PostgreSQL'],['../d6/d31/md_en_2userver_2tutorial_2digest__auth__postgres.html',1,'Digest Authorization/Authentication via PostgreSQL']]],
  ['authorization_20checker_198',['Authorization Checker',['../d6/d31/md_en_2userver_2tutorial_2digest__auth__postgres.html#autotoc_md982',1,'Authorization Checker'],['../da/d24/md_en_2userver_2tutorial_2auth__postgres.html#autotoc_md1076',1,'Authorization Checker']]],
  ['authorization_20factory_199',['Authorization Factory',['../d6/d31/md_en_2userver_2tutorial_2digest__auth__postgres.html#autotoc_md983',1,'Authorization Factory'],['../da/d24/md_en_2userver_2tutorial_2auth__postgres.html#autotoc_md1081',1,'Authorization Factory']]],
  ['auto_200',['connlimit-mode: auto',['../d3/db7/md_en_2userver_2pg_2connlimit__mode__auto.html#autotoc_md755',1,'']]],
  ['auto_20testing_201',['Auto testing',['../dc/d8a/md_en_2userver_2tutorial_2http__caching.html#autotoc_md1197',1,'']]],
  ['automatic_20connection_20limit_202',['uPg: Automatic connection limit',['../d3/db7/md_en_2userver_2pg_2connlimit__mode__auto.html',1,'']]],
  ['automatic_20discovery_203',['Automatic discovery',['../d1/d92/classcomponents_1_1Postgres.html#autotoc_md40',1,'']]],
  ['autotopology_204',['Valkey/Redis Cluster Autotopology',['../dd/dde/md_en_2userver_2redis.html#autotoc_md848',1,'']]],
  ['available_20connections_20found_205',['Error &quot;No available connections found&quot;',['../d3/db7/md_en_2userver_2pg_2connlimit__mode__auto.html#autotoc_md766',1,'']]],
  ['avoid_20missing_20series_20pitfalls_206',['8. Avoid missing-series pitfalls',['../d0/d1b/md_en_2userver_2metrics__migration.html#autotoc_md864',1,'']]],
  ['avoiding_20memory_20leaks_207',['Avoiding memory leaks',['../df/dd1/classcomponents_1_1CachingComponentBase.html#autotoc_md1431',1,'']]],
  ['away_20from_20grpc_20core_20retries_20for_20unary_20calls_20and_20create_20our_20own_20ugrpc_20retries_208',['Why we decided to move away from grpc-core retries for unary calls and create our own ugrpc retries',['../d8/d54/md_en_2userver_2grpc_2timeouts__retries.html#autotoc_md725',1,'']]]
];
