var searchData=
[
  ['package_20for_20ubuntu_0',['Using a prebuilt Debian package for Ubuntu',['../de/dab/md_en_2userver_2build_2build.html#autotoc_md418',1,'']]],
  ['package_20locally_1',['Building Debian package locally',['../de/dab/md_en_2userver_2build_2build.html#autotoc_md399',1,'']]],
  ['package_20maintainers_2',['Distro package maintainers',['../d1/d00/md_en_2userver_2distro__maintainers.html',1,'']]],
  ['package_20using_20docker_3',['Building Debian package using Docker',['../de/dab/md_en_2userver_2build_2build.html#autotoc_md397',1,'']]],
  ['packages_20using_20cpm_4',['Downloading packages using CPM',['../de/dab/md_en_2userver_2build_2build.html#autotoc_md387',1,'']]],
  ['packaging_20operations_5',['Packaging operations',['../d7/d65/md_en_2userver_2mongodb.html#autotoc_md697',1,'']]],
  ['page_6',['Dynamic Web Page',['../d2/d6d/md_en_2userver_2tutorial_2static__content.html#autotoc_md1196',1,'']]],
  ['page_20not_20found_7',['404: Page not Found',['../d8/dee/md_en_2userver_2404.html',1,'']]],
  ['pages_8',['Serving Static Content and Dynamic Web Pages',['../d2/d6d/md_en_2userver_2tutorial_2static__content.html',1,'']]],
  ['paging_9',['Paging',['../d7/dac/md_en_2userver_2scylladb.html#autotoc_md937',1,'Paging'],['../d2/dea/md_en_2userver_2tutorial_2scylla__service.html#autotoc_md1297',1,'Paging']]],
  ['parallel_20loading_10',['Parallel loading',['../d5/d2d/md_en_2userver_2caches.html#autotoc_md255',1,'']]],
  ['parameter_20binding_11',['Statement Preparation and Parameter Binding',['../d4/df5/md_en_2userver_2sqlite_2design__and__details.html#autotoc_md961',1,'']]],
  ['parameterized_20test_12',['Singly-parameterized test.',['../df/d72/structutest_1_1PrintTestName.html#autotoc_md1419',1,'']]],
  ['parametrized_20test_13',['Doubly-parametrized test.',['../df/d72/structutest_1_1PrintTestName.html#autotoc_md1421',1,'']]],
  ['parametrized_20tests_20with_20custom_20names_14',['Parametrized tests with custom names',['../d4/d70/md_en_2userver_2testing.html#autotoc_md1014',1,'']]],
  ['parser_15',['JSON schema chaotic Parser',['../d8/d43/md_en_2userver_2chaotic.html#autotoc_md385',1,'']]],
  ['parsing_20could_20lead_20to_20stackoverflow_16',['CVE-2023-26224: JSON parsing could lead to StackOverflow',['../db/dde/md_en_2userver_2security__changelog.html#autotoc_md947',1,'']]],
  ['parsing_20dynamic_20configs_17',['Parsing dynamic configs',['../d5/d46/md_en_2userver_2dynamic__config.html#autotoc_md530',1,'']]],
  ['parsing_20dynamic_20configs_18',['Recommendations on parsing dynamic configs',['../d5/d46/md_en_2userver_2dynamic__config.html#autotoc_md547',1,'']]],
  ['parsing_20failure_19',['Behavior on config parsing failure',['../dd/d1a/classcomponents_1_1DynamicConfig.html#autotoc_md1462',1,'']]],
  ['parsing_20using_20utils_3a_3aregex_20',['An example of complex string parsing using &lt;span class=&quot;tt&quot;&gt;utils::regex&lt;/span&gt;',['../dd/d3e/classutils_1_1regex.html#autotoc_md1411',1,'']]],
  ['particular_20enable_20disable_20for_20service_20or_20client_21',['Particular enable/disable for service or client',['../dd/d4b/md_en_2userver_2grpc_2middlewares__toggle.html#autotoc_md448',1,'']]],
  ['party_20code_20licenses_22',['Third Party Code Licenses',['../d6/dc8/md__2data_2code_2userver_2THIRD__PARTY.html',1,'']]],
  ['passed_20and_20not_20time_5fpoint_23',['Why is &lt;span class=&quot;tt&quot;&gt;duration&lt;/span&gt; passed and not &lt;span class=&quot;tt&quot;&gt;time_point&lt;/span&gt;',['../d6/d64/md_en_2userver_2deadline__propagation.html#autotoc_md437',1,'']]],
  ['passes_20regardless_20of_20other_20fields_20set_20on_20msg_24',['Passes regardless of other fields set on msg',['../d9/d56/classtestsuite_1_1protobuf_1_1matching_1_1PartialProtobufDict.html#autotoc_md156',1,'']]],
  ['passes_20regardless_20of_20other_20fields_20set_20on_20msg_20or_20on_25',['Passes regardless of other fields set on msg or on',['../de/db3/classtestsuite_1_1protobuf_1_1matching_1_1RecursivePartialProtobufDict.html#autotoc_md157',1,'']]],
  ['path_26',['Graphite metrics by path',['../d9/dac/md_en_2userver_2service__monitor.html#autotoc_md916',1,'']]],
  ['path_20and_20prefix_20semantics_27',['6. Respect &lt;span class=&quot;tt&quot;&gt;path&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;prefix&lt;/span&gt; semantics',['../d0/d1b/md_en_2userver_2metrics__migration.html#autotoc_md847',1,'']]],
  ['path_20example_20with_20errors_20in_20the_20pipeline_28',['The call path example with errors in the pipeline',['../d7/d4b/md_en_2userver_2grpc_2server__middleware__implementation.html#autotoc_md562',1,'']]],
  ['paths_20and_20labels_20correctly_29',['3. Derive paths and labels correctly',['../d0/d1b/md_en_2userver_2metrics__migration.html#autotoc_md829',1,'']]],
  ['paths_20to_20dependencies_30',['CMake options for paths to dependencies',['../d5/d3d/md_en_2userver_2build_2options.html#autotoc_md359',1,'']]],
  ['pattern_31',['You can define matching rule out of pattern',['../de/db0/classtestsuite_1_1matching_1_1Capture.html#autotoc_md159',1,'']]],
  ['per_20call_20rpc_20hooks_20implementation_20example_32',['Per-Call (RPC) hooks implementation example',['../d7/d4b/md_en_2userver_2grpc_2server__middleware__implementation.html#autotoc_md552',1,'']]],
  ['per_20call_20rpc_20hooks_20implementation_20example_33',['Per-call (RPC) hooks implementation example',['../dc/dce/md_en_2userver_2grpc_2client__middleware__implementation.html#autotoc_md433',1,'']]],
  ['per_20client_34',['Enable middlewares per service or per client',['../dd/d4b/md_en_2userver_2grpc_2middlewares__toggle.html#autotoc_md444',1,'']]],
  ['per_20handler_20middleware_20configuration_35',['Per-handler middleware configuration',['../d6/dcc/md_en_2userver_2http__server__middlewares.html#autotoc_md580',1,'']]],
  ['per_20handler_20middleware_20pipelines_36',['Custom per-handler middleware pipelines',['../d6/dcc/md_en_2userver_2http__server__middlewares.html#autotoc_md587',1,'']]],
  ['per_20label_20metrics_37',['Usage of MonotonicByLabelStorage with a group of per-label metrics',['../dc/d4f/classutils_1_1statistics_1_1MonotonicByLabelStorage.html#autotoc_md1540',1,'']]],
  ['per_20message_20hooks_20implementation_20example_38',['Per message hooks implementation example',['../dc/dce/md_en_2userver_2grpc_2client__middleware__implementation.html#autotoc_md438',1,'Per-message hooks implementation example'],['../d7/d4b/md_en_2userver_2grpc_2server__middleware__implementation.html#autotoc_md556',1,'Per-message hooks implementation example']]],
  ['per_20query_20annotations_39',['Per-query annotations',['../d6/de0/md_en_2userver_2sql__files.html#autotoc_md1267',1,'']]],
  ['per_20service_20or_20per_20client_40',['Enable middlewares per service or per client',['../dd/d4b/md_en_2userver_2grpc_2middlewares__toggle.html#autotoc_md444',1,'']]],
  ['per_20test_41',['Changing dynamic configs in testsuite per test',['../d5/d46/md_en_2userver_2dynamic__config.html#autotoc_md591',1,'']]],
  ['performance_42',['Performance',['../d7/d08/md_en_2userver_2intro__io__bound__coro.html#autotoc_md629',1,'']]],
  ['performance_43',['performance',['../de/ddb/md_en_2userver_2driver__guide.html#autotoc_md292',1,'Easy to write, poor performance'],['../de/ddb/md_en_2userver_2driver__guide.html#autotoc_md298',1,'Hard to write, good performance'],['../de/ddb/md_en_2userver_2driver__guide.html#autotoc_md297',1,'Not too easy to write, good performance']]],
  ['performance_20considerations_44',['Performance considerations',['../d0/dc7/classconcurrent_1_1BackgroundTaskStorage.html#autotoc_md1453',1,'']]],
  ['periodic_20update_45',['testsuite-force-periodic-update',['../df/dd1/classcomponents_1_1CachingComponentBase.html#autotoc_md1434',1,'']]],
  ['periodics_20and_20distlocks_46',['Periodics and DistLocks',['../d7/dc4/md_en_2userver_2periodics.html',1,'']]],
  ['periodictask_47',['PeriodicTask',['../d7/dc4/md_en_2userver_2periodics.html#autotoc_md802',1,'']]],
  ['pgo_20clang_48',['PGO (clang)',['../d5/d3d/md_en_2userver_2build_2options.html#autotoc_md412',1,'']]],
  ['ping_49',['Ping',['../db/d69/md_en_2userver_2tutorial_2production__service.html#autotoc_md1287',1,'']]],
  ['ping_50',['ping',['../d2/db4/md_en_2components__schema_2core_2src_2server_2handlers_2ping.html',1,'']]],
  ['pipeline_51',['pipeline',['../db/df2/md_en_2userver_2grpc_2middlewares__order.html#autotoc_md495',1,'Middlewares pipeline'],['../db/d8e/md_en_2components__schema_2core_2src_2middlewares_2pipeline.html',1,'pipeline'],['../d6/dcc/md_en_2userver_2http__server__middlewares.html#autotoc_md584',1,'Server-wide middleware pipeline'],['../d7/d4b/md_en_2userver_2grpc_2server__middleware__implementation.html#autotoc_md562',1,'The call path example with errors in the pipeline']]],
  ['pipeline_5fcomponent_52',['pipeline_component',['../db/dfe/md_en_2components__schema_2core_2src_2clients_2http_2middlewares_2pipeline__component.html',1,'']]],
  ['pipelines_53',['Custom per-handler middleware pipelines',['../d6/dcc/md_en_2userver_2http__server__middlewares.html#autotoc_md587',1,'']]],
  ['pipelines_20configuration_54',['Pipelines configuration',['../d6/dcc/md_en_2userver_2http__server__middlewares.html#autotoc_md583',1,'']]],
  ['pitfalls_55',['pitfalls',['../d0/d1b/md_en_2userver_2metrics__migration.html#autotoc_md864',1,'8. Avoid missing-series pitfalls'],['../da/dd6/md_en_2userver_2cache__dumps.html#autotoc_md288',1,'Nuances and pitfalls']]],
  ['planned_20enhancements_56',['Planned Enhancements',['../d0/db8/md_en_2userver_2kafka.html#autotoc_md568',1,'Planned Enhancements'],['../d2/d5f/md_en_2userver_2mysql_2mysql__driver.html#autotoc_md715',1,'Planned Enhancements']]],
  ['platform_20specific_20build_20dependencies_57',['Platform-specific build dependencies',['../de/db9/md_en_2userver_2build_2dependencies.html#autotoc_md198',1,'']]],
  ['platforms_58',['Platforms',['../d0/dd5/md_en_2userver_2supported__platforms.html',1,'Supported Platforms'],['../d0/dd5/md_en_2userver_2supported__platforms.html#autotoc_md926',1,'Supported Platforms']]],
  ['platforms_59',['platforms',['../d5/d3d/md_en_2userver_2build_2options.html#autotoc_md313',1,'CMake options for features that are unavailable for some platforms'],['../de/db9/md_en_2userver_2build_2dependencies.html#autotoc_md218',1,'Other POSIX based platforms']]],
  ['policy_60',['Security Policy',['../de/d1b/md__2data_2code_2userver_2SECURITY.html',1,'']]],
  ['policy_61',['Cache policy',['../d4/d5f/md_en_2userver_2pg_2cache.html#pg_cc_cache_policy',1,'']]],
  ['pool_20hints_62',['OperationType and Connection Pool Hints',['../d4/df5/md_en_2userver_2sqlite_2design__and__details.html#autotoc_md958',1,'']]],
  ['pooling_20with_20a_20postgresql_20balancer_63',['Transaction pooling with a PostgreSQL balancer',['../d7/dc1/md_en_2userver_2pg_2driver.html#autotoc_md748',1,'']]],
  ['pools_20locking_20strategy_64',['Connection pools &amp;amp; locking strategy',['../d4/df5/md_en_2userver_2sqlite_2design__and__details.html#autotoc_md956',1,'']]],
  ['poor_20performance_65',['Easy to write, poor performance',['../de/ddb/md_en_2userver_2driver__guide.html#autotoc_md292',1,'']]],
  ['portability_20testing_20in_20testsuite_66',['Metrics Portability Testing in Testsuite',['../df/d07/md_en_2userver_2functional__testing.html#autotoc_md694',1,'']]],
  ['posix_20based_20platforms_67',['Other POSIX based platforms',['../de/db9/md_en_2userver_2build_2dependencies.html#autotoc_md218',1,'']]],
  ['postfinish_68',['PreStartCall and PostFinish',['../dc/dce/md_en_2userver_2grpc_2client__middleware__implementation.html#autotoc_md429',1,'']]],
  ['postfinish_20completion_20status_69',['PostFinish completion status',['../dc/dce/md_en_2userver_2grpc_2client__middleware__implementation.html#autotoc_md432',1,'']]],
  ['postgres_70',['Deadline propagation details for Postgres',['../d6/d64/md_en_2userver_2deadline__propagation.html#autotoc_md487',1,'']]],
  ['postgres_20driver_20features_71',['Postgres driver Features',['../d7/dc1/md_en_2userver_2pg_2driver.html#autotoc_md740',1,'']]],
  ['postgres_20errors_72',['uPg: Postgres errors',['../d3/d00/md_en_2userver_2pg_2errors.html',1,'']]],
  ['postgres_5fcongestion_5fcontrol_5fsettings_73',['POSTGRES_CONGESTION_CONTROL_SETTINGS',['../d5/d3b/md_en_2dynamic__configs_2POSTGRES__CONGESTION__CONTROL__SETTINGS.html',1,'']]],
  ['postgres_5fcongestion_5fcontrol_5fsettings_20dynamic_20config_74',['POSTGRES_CONGESTION_CONTROL_SETTINGS Dynamic Config',['../d5/d3b/md_en_2dynamic__configs_2POSTGRES__CONGESTION__CONTROL__SETTINGS.html#autotoc_md59',1,'']]],
  ['postgres_5fconnection_5fpool_5fsettings_75',['POSTGRES_CONNECTION_POOL_SETTINGS',['../d0/db5/md_en_2dynamic__configs_2POSTGRES__CONNECTION__POOL__SETTINGS.html',1,'']]],
  ['postgres_5fconnection_5fpool_5fsettings_20dynamic_20config_76',['POSTGRES_CONNECTION_POOL_SETTINGS Dynamic Config',['../d0/db5/md_en_2dynamic__configs_2POSTGRES__CONNECTION__POOL__SETTINGS.html#autotoc_md64',1,'']]],
  ['postgres_5fconnection_5fsettings_77',['POSTGRES_CONNECTION_SETTINGS',['../dc/dea/md_en_2dynamic__configs_2POSTGRES__CONNECTION__SETTINGS.html',1,'']]],
  ['postgres_5fconnection_5fsettings_20dynamic_20config_78',['POSTGRES_CONNECTION_SETTINGS Dynamic Config',['../dc/dea/md_en_2dynamic__configs_2POSTGRES__CONNECTION__SETTINGS.html#autotoc_md61',1,'']]],
  ['postgres_5fconnlimit_5fmode_5fauto_5fenabled_79',['POSTGRES_CONNLIMIT_MODE_AUTO_ENABLED',['../d6/d84/md_en_2dynamic__configs_2POSTGRES__CONNLIMIT__MODE__AUTO__ENABLED.html',1,'']]],
  ['postgres_5fconnlimit_5fmode_5fauto_5fenabled_20dynamic_20config_80',['POSTGRES_CONNLIMIT_MODE_AUTO_ENABLED Dynamic Config',['../d6/d84/md_en_2dynamic__configs_2POSTGRES__CONNLIMIT__MODE__AUTO__ENABLED.html#autotoc_md60',1,'']]],
  ['postgres_5fdefault_5fcommand_5fcontrol_81',['POSTGRES_DEFAULT_COMMAND_CONTROL',['../d1/df4/md_en_2dynamic__configs_2POSTGRES__DEFAULT__COMMAND__CONTROL.html',1,'']]],
  ['postgres_5fdefault_5fcommand_5fcontrol_20dynamic_20config_82',['POSTGRES_DEFAULT_COMMAND_CONTROL Dynamic Config',['../d1/df4/md_en_2dynamic__configs_2POSTGRES__DEFAULT__COMMAND__CONTROL.html#autotoc_md62',1,'']]],
  ['postgres_5fdistlock_5fsettings_83',['POSTGRES_DISTLOCK_SETTINGS',['../dd/ddc/md_en_2dynamic__configs_2POSTGRES__DISTLOCK__SETTINGS.html',1,'']]],
  ['postgres_5fdistlock_5fsettings_20dynamic_20config_84',['POSTGRES_DISTLOCK_SETTINGS Dynamic Config',['../dd/ddc/md_en_2dynamic__configs_2POSTGRES__DISTLOCK__SETTINGS.html#autotoc_md63',1,'']]],
  ['postgres_5fhandlers_5fcommand_5fcontrol_85',['POSTGRES_HANDLERS_COMMAND_CONTROL',['../d8/d4c/md_en_2dynamic__configs_2POSTGRES__HANDLERS__COMMAND__CONTROL.html',1,'']]],
  ['postgres_5fhandlers_5fcommand_5fcontrol_20dynamic_20config_86',['POSTGRES_HANDLERS_COMMAND_CONTROL Dynamic Config',['../d8/d4c/md_en_2dynamic__configs_2POSTGRES__HANDLERS__COMMAND__CONTROL.html#autotoc_md65',1,'']]],
  ['postgres_5fqueries_5fcommand_5fcontrol_87',['POSTGRES_QUERIES_COMMAND_CONTROL',['../d4/d7a/md_en_2dynamic__configs_2POSTGRES__QUERIES__COMMAND__CONTROL.html',1,'']]],
  ['postgres_5fqueries_5fcommand_5fcontrol_20dynamic_20config_88',['POSTGRES_QUERIES_COMMAND_CONTROL Dynamic Config',['../d4/d7a/md_en_2dynamic__configs_2POSTGRES__QUERIES__COMMAND__CONTROL.html#autotoc_md71',1,'']]],
  ['postgres_5fstatement_5fmetrics_5fsettings_89',['POSTGRES_STATEMENT_METRICS_SETTINGS',['../d9/da1/md_en_2dynamic__configs_2POSTGRES__STATEMENT__METRICS__SETTINGS.html',1,'']]],
  ['postgres_5fstatement_5fmetrics_5fsettings_20dynamic_20config_90',['POSTGRES_STATEMENT_METRICS_SETTINGS Dynamic Config',['../d9/da1/md_en_2dynamic__configs_2POSTGRES__STATEMENT__METRICS__SETTINGS.html#autotoc_md66',1,'']]],
  ['postgres_5ftopology_5fsettings_91',['POSTGRES_TOPOLOGY_SETTINGS',['../dd/da3/md_en_2dynamic__configs_2POSTGRES__TOPOLOGY__SETTINGS.html',1,'']]],
  ['postgres_5ftopology_5fsettings_20dynamic_20config_92',['POSTGRES_TOPOLOGY_SETTINGS Dynamic Config',['../dd/da3/md_en_2dynamic__configs_2POSTGRES__TOPOLOGY__SETTINGS.html#autotoc_md67',1,'']]],
  ['postgresql_93',['PostgreSQL',['../d7/dc4/md_en_2userver_2pg_2types.html#autotoc_md889',1,'Arrays in PostgreSQL'],['../d7/dc4/md_en_2userver_2pg_2types.html#autotoc_md899',1,'Bit string types in PostgreSQL'],['../d7/dc4/md_en_2userver_2pg_2types.html#autotoc_md893',1,'C++ strong typedefs in PostgreSQL'],['../d4/d5f/md_en_2userver_2pg_2cache.html',1,'Caching Component for PostgreSQL'],['../da/d24/md_en_2userver_2tutorial_2auth__postgres.html',1,'Custom Authorization/Authentication via PostgreSQL'],['../d6/d31/md_en_2userver_2tutorial_2digest__auth__postgres.html',1,'Digest Authorization/Authentication via PostgreSQL'],['../d7/dc4/md_en_2userver_2pg_2types.html#autotoc_md895',1,'Geometry types in PostgreSQL'],['../d7/dc4/md_en_2userver_2pg_2types.html#autotoc_md887',1,'How not to get skewed times in the PostgreSQL'],['../d7/dc4/md_en_2userver_2pg_2types.html#autotoc_md897',1,'Network types in PostgreSQL'],['../de/d6a/md_en_2index.html#autotoc_md126',1,'PostgreSQL'],['../d5/da0/md_en_2userver_2pg_2user__types.html#autotoc_md906',1,'Time Range and Other Widely Used Types in PostgreSQL']]],
  ['postgresql_20→_20c_20type_20mapping_94',['PostgreSQL → C++ type mapping',['../d6/de0/md_en_2userver_2sql__files.html#autotoc_md1236',1,'']]],
  ['postgresql_20and_20locally_20differ_20for_20multiple_20hours_20minutes_95',['PostgreSQL: Timestamp in PostgreSQL and locally differ for multiple hours/minutes',['../de/d61/md_en_2userver_2faq.html#autotoc_md416',1,'']]],
  ['postgresql_20balancer_96',['Transaction pooling with a PostgreSQL balancer',['../d7/dc1/md_en_2userver_2pg_2driver.html#autotoc_md748',1,'']]],
  ['postgresql_20bytea_20support_97',['PostgreSQL bytea support',['../d7/dc4/md_en_2userver_2pg_2types.html#autotoc_md896',1,'']]],
  ['postgresql_20cache_98',['PostgreSQL Cache',['../da/d24/md_en_2userver_2tutorial_2auth__postgres.html#autotoc_md1072',1,'']]],
  ['postgresql_20domain_20user_20type_99',['Mapping a C++ type to PostgreSQL domain user type',['../d5/da0/md_en_2userver_2pg_2user__types.html#autotoc_md890',1,'']]],
  ['postgresql_20dto_20codegen_100',['PostgreSQL DTO codegen',['../d6/de0/md_en_2userver_2sql__files.html#autotoc_md1127',1,'']]],
  ['postgresql_20enum_20type_101',['Mapping a C++ enum to PostgreSQL enum type',['../d5/da0/md_en_2userver_2pg_2user__types.html#autotoc_md898',1,'']]],
  ['postgresql_20license_102',['PostgreSQL License',['../d6/dc8/md__2data_2code_2userver_2THIRD__PARTY.html#autotoc_md197',1,'']]],
  ['postgresql_20ranges_103',['PostgreSQL ranges',['../d7/dc4/md_en_2userver_2pg_2types.html#autotoc_md894',1,'']]],
  ['postgresql_20results_104',['uPg: Typed PostgreSQL results',['../d5/d53/md_en_2userver_2pg_2user__row__types.html',1,'']]],
  ['postgresql_20service_105',['PostgreSQL service',['../d4/d31/md_en_2userver_2tutorial_2postgres__service.html',1,'']]],
  ['postgresql_20table_106',['PostgreSQL Table',['../d6/d31/md_en_2userver_2tutorial_2digest__auth__postgres.html#autotoc_md981',1,'']]],
  ['postgresql_20text_107',['Mapping C++ enums to PostgreSQL text',['../d5/da0/md_en_2userver_2pg_2user__types.html#autotoc_md903',1,'']]],
  ['postgresql_20types_108',['PostgreSQL types',['../d7/dc4/md_en_2userver_2pg_2types.html#autotoc_md866',1,'Fundamental PostgreSQL types'],['../d7/dc4/md_en_2userver_2pg_2types.html#autotoc_md891',1,'User-defined PostgreSQL types']]],
  ['postgresql_20types_20not_20covered_20above_109',['PostgreSQL types not covered above',['../d7/dc4/md_en_2userver_2pg_2types.html#autotoc_md900',1,'']]],
  ['postgresql_20user_20type_20mappings_110',['uPg: PostgreSQL user type mappings',['../d5/da0/md_en_2userver_2pg_2user__types.html',1,'']]],
  ['postgresql_20versions_111',['PostgreSQL versions',['../de/db9/md_en_2userver_2build_2dependencies.html#autotoc_md219',1,'']]],
  ['postgresql_3a_20something_20is_20slow_112',['PostgreSQL: Something is slow',['../de/d61/md_en_2userver_2faq.html#autotoc_md413',1,'']]],
  ['postgresql_3a_20statement_20xxxx_20network_20timeout_20error_113',['PostgreSQL: Statement XXXX network timeout error',['../de/d61/md_en_2userver_2faq.html#autotoc_md409',1,'']]],
  ['postgresql_3a_20statement_20xxxx_20was_20canceled_114',['PostgreSQL: Statement XXXX was canceled',['../de/d61/md_en_2userver_2faq.html#autotoc_md411',1,'']]],
  ['postgresql_3a_20timestamp_20in_20postgresql_20and_20locally_20differ_20for_20multiple_20hours_20minutes_115',['PostgreSQL: Timestamp in PostgreSQL and locally differ for multiple hours/minutes',['../de/d61/md_en_2userver_2faq.html#autotoc_md416',1,'']]],
  ['postrecvmessage_116',['PreSendMessage and PostRecvMessage',['../dc/dce/md_en_2userver_2grpc_2client__middleware__implementation.html#autotoc_md436',1,'']]],
  ['postrecvmessage_20and_20presendmessage_117',['PostRecvMessage and PreSendMessage',['../d7/d4b/md_en_2userver_2grpc_2server__middleware__implementation.html#autotoc_md555',1,'']]],
  ['pprof_20protocol_118',['Usage of the &lt;span class=&quot;tt&quot;&gt;pprof&lt;/span&gt; protocol',['../d2/d34/classserver_1_1handlers_1_1Jemalloc.html#autotoc_md1521',1,'']]],
  ['pr_119',['Issue, feature and pull requests (PR)',['../d0/d7b/md_en_2userver_2development_2releases.html#autotoc_md270',1,'']]],
  ['practices_120',['Production configs and best practices',['../db/d69/md_en_2userver_2tutorial_2production__service.html',1,'']]],
  ['pre_20announce_20may_20jul_202022_121',['Pre announce (May-Jul 2022)',['../dd/d6f/md_en_2userver_2roadmap__and__changelog__v1.html#autotoc_md1375',1,'']]],
  ['pre_20caching_20data_20from_20http_20remote_122',['Pre-caching data from HTTP remote',['../dc/d8a/md_en_2userver_2tutorial_2http__caching.html',1,'']]],
  ['prebuilt_20debian_20package_20for_20ubuntu_123',['Using a prebuilt Debian package for Ubuntu',['../de/dab/md_en_2userver_2build_2build.html#autotoc_md418',1,'']]],
  ['precedence_20rules_20of_20dynamic_20config_20modification_20in_20testsuite_124',['Precedence rules of dynamic config modification in testsuite',['../d5/d46/md_en_2userver_2dynamic__config.html#autotoc_md603',1,'']]],
  ['predefined_20roles_125',['Predefined roles',['../d1/d92/classcomponents_1_1Postgres.html#autotoc_md39',1,'']]],
  ['prefix_126',['Prometheus metrics by prefix',['../d9/dac/md_en_2userver_2service__monitor.html#autotoc_md915',1,'']]],
  ['prefix_20semantics_127',['6. Respect &lt;span class=&quot;tt&quot;&gt;path&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;prefix&lt;/span&gt; semantics',['../d0/d1b/md_en_2userver_2metrics__migration.html#autotoc_md847',1,'']]],
  ['prefixes_20and_20labels_128',['9. Use &lt;span class=&quot;tt&quot;&gt;sliced()&lt;/span&gt; to remove repeated prefixes and labels',['../d0/d1b/md_en_2userver_2metrics__migration.html#autotoc_md869',1,'']]],
  ['preparation_20and_20parameter_20binding_129',['Statement Preparation and Parameter Binding',['../d4/df5/md_en_2userver_2sqlite_2design__and__details.html#autotoc_md961',1,'']]],
  ['preparations_130',['Preparations',['../d5/db9/md_en_2userver_2tutorial_2grpc__middleware__service.html#autotoc_md1052',1,'Preparations'],['../d6/daa/md_en_2userver_2tutorial_2grpc__service.html#autotoc_md1136',1,'Preparations'],['../d6/daa/md_en_2userver_2tutorial_2grpc__service.html#autotoc_md1170',1,'Preparations']]],
  ['presendmessage_131',['PostRecvMessage and PreSendMessage',['../d7/d4b/md_en_2userver_2grpc_2server__middleware__implementation.html#autotoc_md555',1,'']]],
  ['presendmessage_20and_20postrecvmessage_132',['PreSendMessage and PostRecvMessage',['../dc/dce/md_en_2userver_2grpc_2client__middleware__implementation.html#autotoc_md436',1,'']]],
  ['prestartcall_20and_20postfinish_133',['PreStartCall and PostFinish',['../dc/dce/md_en_2userver_2grpc_2client__middleware__implementation.html#autotoc_md429',1,'']]],
  ['pretty_20printers_134',['Custom pretty-printers',['../d2/d1b/md_en_2userver_2gdb__debugging.html#autotoc_md449',1,'']]],
  ['pretty_20printers_20and_20commands_135',['Adding new pretty-printers and commands',['../d2/d1b/md_en_2userver_2gdb__debugging.html#autotoc_md470',1,'']]],
  ['primitives_136',['Primitives',['../d1/d9a/md_en_2userver_2metrics.html#autotoc_md769',1,'Additional Primitives'],['../d6/d6c/md_en_2userver_2synchronization.html#autotoc_md1089',1,'Cancellations, Cancellation Blockers and Synchronization Primitives'],['../d6/d6c/md_en_2userver_2synchronization.html',1,'Synchronization Primitives']]],
  ['primitives_137',['primitives',['../d0/dd8/md_en_2userver_2lru__cache.html#autotoc_md598',1,'Low level primitives'],['../d6/d6c/md_en_2userver_2synchronization.html#autotoc_md1096',1,'Synchronization mechanisms and primitives']]],
  ['primitives_20for_20metrics_138',['Basic Primitives for Metrics',['../d1/d9a/md_en_2userver_2metrics.html#autotoc_md763',1,'']]],
  ['printers_139',['Custom pretty-printers',['../d2/d1b/md_en_2userver_2gdb__debugging.html#autotoc_md449',1,'']]],
  ['printers_20and_20commands_140',['Adding new pretty-printers and commands',['../d2/d1b/md_en_2userver_2gdb__debugging.html#autotoc_md470',1,'']]],
  ['process_20all_20the_20remaining_20items_20during_20shutdown_141',['Using queue closing mechanic to process all the remaining items during shutdown',['../d6/d6c/md_en_2userver_2synchronization.html#autotoc_md1155',1,'']]],
  ['process_5fstarter_142',['process_starter',['../d1/d30/md_en_2components__schema_2core_2src_2components_2process__starter.html',1,'']]],
  ['processor_143',['processor',['../db/d90/md_en_2userver_2task__processors__guide.html#autotoc_md998',1,'fs-task-processor'],['../db/d90/md_en_2userver_2task__processors__guide.html#autotoc_md994',1,'main-task-processor'],['../db/d90/md_en_2userver_2task__processors__guide.html#autotoc_md1005',1,'monitor-task-processor'],['../db/d90/md_en_2userver_2task__processors__guide.html#autotoc_md1007',1,'Moving CPU-bound tasks to a separate task processor']]],
  ['processors_144',['Common Task Processors',['../db/d90/md_en_2userver_2task__processors__guide.html#autotoc_md991',1,'']]],
  ['processors_145',['processors',['../db/d90/md_en_2userver_2task__processors__guide.html#autotoc_md1003',1,'single-threaded-task-processors'],['../db/d69/md_en_2userver_2tutorial_2production__service.html#autotoc_md1268',1,'Task processors']]],
  ['processsocket_146',['ProcessSocket',['../dc/d93/md_en_2userver_2tutorial_2tcp__service.html#autotoc_md1223',1,'ProcessSocket'],['../db/db9/md_en_2userver_2tutorial_2tcp__full.html#autotoc_md1222',1,'ProcessSocket']]],
  ['produce_20message_20on_20http_20request_147',['Produce message on HTTP request',['../d9/d1c/md_en_2userver_2tutorial_2kafka__service.html#autotoc_md1266',1,'']]],
  ['produce_20messages_20to_20topic_148',['Produce messages to topic',['../d9/d1c/md_en_2userver_2tutorial_2kafka__service.html#autotoc_md1262',1,'']]],
  ['producer_20declaration_149',['HTTP handler component (producer) declaration',['../d9/d1c/md_en_2userver_2tutorial_2kafka__service.html#autotoc_md1259',1,'']]],
  ['producer_20features_150',['Producer Features',['../d0/db8/md_en_2userver_2kafka.html#autotoc_md548',1,'']]],
  ['producer_5fcomponent_151',['producer_component',['../d8/d9c/md_en_2components__schema_2kafka_2src_2kafka_2producer__component.html',1,'']]],
  ['producers_152',['Using queue closing mechanic to stop the producers',['../d6/d6c/md_en_2userver_2synchronization.html#autotoc_md1173',1,'']]],
  ['production_20configs_20and_20best_20practices_153',['Production configs and best practices',['../db/d69/md_en_2userver_2tutorial_2production__service.html',1,'']]],
  ['production_20service_154',['production service',['../db/d69/md_en_2userver_2tutorial_2production__service.html#autotoc_md1299',1,'Dynamic configs of a sample production service'],['../d4/d1a/md_en_2userver_2memory__profile__running__service.html',1,'Memory profiling a production service']]],
  ['production_20setup_20with_20balancer_155',['Production setup with balancer',['../d2/d58/md_en_2userver_2deploy__env.html#autotoc_md355',1,'']]],
  ['production_20setup_20with_20service_20mesh_156',['Production setup with service-mesh',['../d2/d58/md_en_2userver_2deploy__env.html#autotoc_md370',1,'']]],
  ['production_20use_157',['Is userver ready for production use?',['../d0/d7b/md_en_2userver_2development_2releases.html#autotoc_md252',1,'']]],
  ['profile_20a_20running_20service_158',['How to profile a running service',['../d4/d1a/md_en_2userver_2memory__profile__running__service.html#autotoc_md612',1,'']]],
  ['profile_20a_20service_159',['How to profile a service',['../db/d8f/md_en_2userver_2profile__context__switches.html#autotoc_md844',1,'']]],
  ['profile_20at_20service_20start_160',['How to profile at service start',['../d4/d1a/md_en_2userver_2memory__profile__running__service.html#autotoc_md614',1,'']]],
  ['profiles_161',['What to search in profiles',['../db/d8f/md_en_2userver_2profile__context__switches.html#autotoc_md850',1,'']]],
  ['profiling_20a_20production_20service_162',['Memory profiling a production service',['../d4/d1a/md_en_2userver_2memory__profile__running__service.html',1,'']]],
  ['profiling_20context_20switches_163',['Profiling context switches',['../db/d8f/md_en_2userver_2profile__context__switches.html',1,'']]],
  ['project_164',['Creating a new service project',['../de/dab/md_en_2userver_2build_2build.html#autotoc_md366',1,'']]],
  ['projects_165',['Use userver in your projects',['../de/dab/md_en_2userver_2build_2build.html#autotoc_md405',1,'']]],
  ['prometheus_20graphite_20and_20default_20metrics_20description_166',['Retrieving Service Statistics and Metrics (Prometheus/Graphite/...) and Default Metrics Description',['../d9/dac/md_en_2userver_2service__monitor.html',1,'']]],
  ['prometheus_20metrics_20by_20prefix_167',['Prometheus metrics by prefix',['../d9/dac/md_en_2userver_2service__monitor.html#autotoc_md915',1,'']]],
  ['propagation_168',['propagation',['../d6/d64/md_en_2userver_2deadline__propagation.html#autotoc_md430',1,'A classic example of deadline propagation'],['../d6/d64/md_en_2userver_2deadline__propagation.html#autotoc_md453',1,'Blocking the deadline propagation'],['../d6/d64/md_en_2userver_2deadline__propagation.html',1,'Deadline propagation']]],
  ['propagation_20details_20for_20grpc_20clients_169',['Deadline propagation details for gRPC clients',['../d6/d64/md_en_2userver_2deadline__propagation.html#autotoc_md479',1,'']]],
  ['propagation_20details_20for_20grpc_20service_20implementations_170',['Deadline propagation details for gRPC service implementations',['../d6/d64/md_en_2userver_2deadline__propagation.html#autotoc_md465',1,'']]],
  ['propagation_20details_20for_20http_20handlers_171',['Deadline propagation details for HTTP handlers',['../d6/d64/md_en_2userver_2deadline__propagation.html#autotoc_md457',1,'']]],
  ['propagation_20details_20for_20mongo_172',['Deadline propagation details for Mongo',['../d6/d64/md_en_2userver_2deadline__propagation.html#autotoc_md483',1,'']]],
  ['propagation_20details_20for_20postgres_173',['Deadline propagation details for Postgres',['../d6/d64/md_en_2userver_2deadline__propagation.html#autotoc_md487',1,'']]],
  ['propagation_20details_20for_20redis_174',['Deadline propagation details for Redis',['../d6/d64/md_en_2userver_2deadline__propagation.html#autotoc_md489',1,'']]],
  ['propagation_20details_20for_20the_20http_20client_175',['Deadline propagation details for the HTTP client',['../d6/d64/md_en_2userver_2deadline__propagation.html#autotoc_md472',1,'']]],
  ['propagation_20http_20headers_176',['Deadline Propagation HTTP headers',['../d6/d64/md_en_2userver_2deadline__propagation.html#autotoc_md441',1,'']]],
  ['propagation_20work_177',['Why doesn&apos;t &quot;close propagation&quot; work',['../d6/d64/md_en_2userver_2deadline__propagation.html#autotoc_md431',1,'']]],
  ['protocol_178',['protocol',['../df/d0c/md_en_2userver_2logging.html#autotoc_md872',1,'OpenTelemetry protocol'],['../d2/d34/classserver_1_1handlers_1_1Jemalloc.html#autotoc_md1521',1,'Usage of the &lt;span class=&quot;tt&quot;&gt;pprof&lt;/span&gt; protocol']]],
  ['protocols_179',['Protocols',['../de/d6a/md_en_2index.html#autotoc_md123',1,'']]],
  ['prototyping_180',['Easy - library for single file prototyping',['../da/de8/md_en_2userver_2libraries_2easy.html',1,'']]],
  ['provided_181',['Guarantees provided',['../d7/dc4/md_en_2userver_2periodics.html#autotoc_md808',1,'']]],
  ['provider_5fcomponent_182',['provider_component',['../d9/d5c/md_en_2components__schema_2core_2src_2storages_2secdist_2provider__component.html',1,'']]],
  ['proxy_183',['Proxy',['../df/d37/md_en_2userver_2chaotic__clients.html#autotoc_md230',1,'']]],
  ['public_20disclosure_20timing_184',['Public Disclosure Timing',['../de/d1b/md__2data_2code_2userver_2SECURITY.html#autotoc_md145',1,'']]],
  ['publications_20and_20videos_185',['Publications and Videos',['../dc/d30/md_en_2userver_2publications.html',1,'']]],
  ['pull_20requests_186',['Releases, Trunk-based Development and Pull Requests',['../d0/d7b/md_en_2userver_2development_2releases.html',1,'']]],
  ['pull_20requests_20pr_187',['Issue, feature and pull requests (PR)',['../d0/d7b/md_en_2userver_2development_2releases.html#autotoc_md270',1,'']]],
  ['put_188',['PUT',['../dd/dea/classserver_1_1handlers_1_1DynamicDebugLog.html#autotoc_md1509',1,'']]],
  ['pytest_5fuserver_189',['pytest_userver',['../df/d07/md_en_2userver_2functional__testing.html#autotoc_md630',1,'']]],
  ['python_20environment_190',['Python environment',['../df/d07/md_en_2userver_2functional__testing.html#autotoc_md620',1,'']]]
];
