var searchData=
[
  ['schemas_0',['Dynamic config schemas',['../de/d10/md_en_2schemas_2dynamic__configs.html',1,'']]],
  ['security_20changelog_1',['Security Changelog',['../db/dde/md_en_2userver_2security__changelog.html',1,'']]],
  ['security_20policy_2',['Security Policy',['../d6/d2d/md__2data_2code_2service__template_2third__party_2userver_2SECURITY.html',1,'']]],
  ['server_3',['server',['../da/d16/md_en_2userver_2tutorial_2hello__service.html',1,'Writing your first HTTP server'],['../d4/d95/md_en_2userver_2tutorial_2config__service.html',1,'Writing your own configs server']]],
  ['server_20with_20metrics_20and_20spans_4',['TCP full-duplex server with metrics and Spans',['../db/db9/md_en_2userver_2tutorial_2tcp__full.html',1,'']]],
  ['server_20with_20static_20configs_20validation_5',['TCP half-duplex server with static configs validation',['../dc/d93/md_en_2userver_2tutorial_2tcp__service.html',1,'']]],
  ['service_6',['service',['../d6/daa/md_en_2userver_2tutorial_2grpc__service.html',1,'gRPC client and service'],['../d4/d1a/md_en_2userver_2memory__profile__running__service.html',1,'Memory profiling a production service'],['../d5/d81/md_en_2userver_2tutorial_2mongo__service.html',1,'MongoDB service'],['../d4/d31/md_en_2userver_2tutorial_2postgres__service.html',1,'PostgreSQL service'],['../d3/da2/md_en_2userver_2tutorial_2redis__service.html',1,'Redis service'],['../d7/d9e/md_en_2userver_2tutorial_2websocket__service.html',1,'Writing your WebSocket service']]],
  ['service_20statistics_20and_20metrics_20prometheus_20graphite_7',['Service Statistics and Metrics (Prometheus/Graphite/...)',['../d9/dac/md_en_2userver_2service__monitor.html',1,'']]],
  ['service_20tests_20testsuite_8',['Functional service tests (testsuite)',['../df/d07/md_en_2userver_2functional__testing.html',1,'']]],
  ['sets_9',['uPg: Working with result sets',['../db/db5/pg_process_results.html',1,'']]],
  ['signals_10',['Handling OS signals',['../df/d4e/md_en_2userver_2os__signals.html',1,'']]],
  ['spans_11',['TCP full-duplex server with metrics and Spans',['../db/db9/md_en_2userver_2tutorial_2tcp__full.html',1,'']]],
  ['specific_20configurations_12',['Deploy Environment Specific Configurations',['../d2/d58/md_en_2userver_2deploy__env.html',1,'']]],
  ['stability_20versioning_13',['API and ABI stability, versioning',['../db/d57/md_en_2userver_2development_2stability.html',1,'']]],
  ['static_20configs_20validation_14',['TCP half-duplex server with static configs validation',['../dc/d93/md_en_2userver_2tutorial_2tcp__service.html',1,'']]],
  ['statistics_20and_20metrics_20prometheus_20graphite_15',['Service Statistics and Metrics (Prometheus/Graphite/...)',['../d9/dac/md_en_2userver_2service__monitor.html',1,'']]],
  ['strong_20typedef_20idiom_16',['uPg: support for C++ &apos;strong typedef&apos; idiom',['../d3/ddf/pg_strong_typedef.html',1,'']]],
  ['support_17',['uPg timestamp support',['../df/d8a/pg_timestamp.html',1,'']]],
  ['support_20for_20c_20strong_20typedef_20idiom_18',['uPg: support for C++ &apos;strong typedef&apos; idiom',['../d3/ddf/pg_strong_typedef.html',1,'']]],
  ['supported_20data_20types_19',['uPg: Supported data types',['../d0/d89/pg_types.html',1,'']]],
  ['supported_20platforms_20',['Supported Platforms',['../d0/dd5/md_en_2userver_2supported__platforms.html',1,'']]],
  ['supported_20types_21',['MySQL supported types',['../d2/d0a/md_en_2userver_2mysql_2supported__types.html',1,'']]],
  ['switches_22',['Profiling context switches',['../db/d8f/md_en_2userver_2profile__context__switches.html',1,'']]],
  ['synchronization_20primitives_23',['Synchronization Primitives',['../d6/d6c/md_en_2userver_2synchronization.html',1,'']]],
  ['system_24',['Component system',['../dc/dcc/md_en_2userver_2component__system.html',1,'']]]
];
