var namespaceconcurrent =
[
    [ "AsyncEventChannel", "d6/d38/classconcurrent_1_1AsyncEventChannel.html", "d6/d38/classconcurrent_1_1AsyncEventChannel" ],
    [ "AsyncEventSource", "dc/d11/classconcurrent_1_1AsyncEventSource.html", "dc/d11/classconcurrent_1_1AsyncEventSource" ],
    [ "AsyncEventSubscriberScope", "dd/de6/classconcurrent_1_1AsyncEventSubscriberScope.html", "dd/de6/classconcurrent_1_1AsyncEventSubscriberScope" ],
    [ "BackgroundTaskStorage", "d0/dc7/classconcurrent_1_1BackgroundTaskStorage.html", "d0/dc7/classconcurrent_1_1BackgroundTaskStorage" ],
    [ "BackgroundTaskStorageCore", "d9/d0a/classconcurrent_1_1BackgroundTaskStorageCore.html", "d9/d0a/classconcurrent_1_1BackgroundTaskStorageCore" ],
    [ "ConflatedEventChannel", "d2/d89/classconcurrent_1_1ConflatedEventChannel.html", "d2/d89/classconcurrent_1_1ConflatedEventChannel" ],
    [ "Consumer", "dc/dd1/classconcurrent_1_1Consumer.html", "dc/dd1/classconcurrent_1_1Consumer" ],
    [ "FunctionId", "d8/dd3/classconcurrent_1_1FunctionId.html", "d8/dd3/classconcurrent_1_1FunctionId" ],
    [ "GenericQueue", "d8/d97/classconcurrent_1_1GenericQueue.html", "d8/d97/classconcurrent_1_1GenericQueue" ],
    [ "ItemMutex", "db/dce/classconcurrent_1_1ItemMutex.html", null ],
    [ "LazyValue", "d5/d2a/classconcurrent_1_1LazyValue.html", "d5/d2a/classconcurrent_1_1LazyValue" ],
    [ "LockedPtr", "dc/dfe/classconcurrent_1_1LockedPtr.html", "dc/dfe/classconcurrent_1_1LockedPtr" ],
    [ "MpscQueue", "d0/d92/classconcurrent_1_1MpscQueue.html", "d0/d92/classconcurrent_1_1MpscQueue" ],
    [ "MutexSet", "d5/d09/classconcurrent_1_1MutexSet.html", "d5/d09/classconcurrent_1_1MutexSet" ],
    [ "Producer", "da/dce/classconcurrent_1_1Producer.html", "da/dce/classconcurrent_1_1Producer" ],
    [ "StripedCounter", "d2/db6/classconcurrent_1_1StripedCounter.html", "d2/db6/classconcurrent_1_1StripedCounter" ],
    [ "Variable", "db/d57/classconcurrent_1_1Variable.html", "db/d57/classconcurrent_1_1Variable" ],
    [ "NonFifoMpmcQueue", "dc/db7/group__userver__concurrency.html#ga564b6fabf9ca1dc0dfa7c5ec3f3172ef", null ],
    [ "NonFifoMpscQueue", "dc/db7/group__userver__concurrency.html#ga932e4409d1cd0c740a04567c0b778efd", null ],
    [ "SpmcQueue", "dc/db7/group__userver__concurrency.html#gad3ba33f3d929534956f5fda667ba32dc", null ],
    [ "SpscQueue", "dc/db7/group__userver__concurrency.html#ga1f9856ce2c9662e47a69725e04aa9e5c", null ],
    [ "StringStreamQueue", "dc/db7/group__userver__concurrency.html#ga24465b72cfc96b187a1e2666c6326ce5", null ]
];